-- Engenharia de Produção — carga no schema taxonomia
-- Gerado a partir de ENGENHARIA_PRODUCAO.md (Parte I)
-- 20 disciplinas, 67 assuntos, 227 subassuntos
--
-- Vincula as disciplinas à família já existente ENGPRO ("Engenharia de Produção") em taxonomia._familias.
-- Assuntos e subassuntos também recebem familia_id (denormalizado).
-- O script é idempotente (upsert por chave primária) e roda em uma única transação.
-- Pré-requisito: coluna familia_id já existe em assuntos e subassuntos
--   (rode taxonomia_add_familia_id_assuntos_subassuntos.sql antes, se ainda não rodou).

begin;

insert into taxonomia.disciplinas (disciplina_id, familia_id, name, ordem, ativo)
select d.disciplina_id, 'ENGPRO', d.name, d.ordem, true
from (values
  ('ECO', 'Economia', 1),
  ('ENG_MET', 'Engenharia de Métodos', 2),
  ('ENG_PRO', 'Engenharia do Produto', 3),
  ('ENG_TRAB', 'Engenharia do Trabalho', 4),
  ('ERG', 'Ergonomia', 5),
  ('GES_INO', 'Gestão da Inovação e Tecnologia', 6),
  ('GES_CUS', 'Gestão de Custos', 7),
  ('GES_OPE', 'Gestão de Operações', 8),
  ('GES_PES', 'Gestão de Pessoas', 9),
  ('GES_PROJ', 'Gestão de Projetos', 10),
  ('GES_EST', 'Gestão Estratégica', 11),
  ('GES_FIN', 'Gestão Financeira e Investimentos', 12),
  ('GES_ORG', 'Gestão Organizacional', 13),
  ('LOG_CAD', 'Logística e Cadeia de Suprimentos', 14),
  ('MAN_CONF', 'Manutenção e Confiabilidade', 15),
  ('PES_OP', 'Pesquisa Operacional', 16),
  ('PCP', 'Planejamento e Controle da Produção', 17),
  ('QUA', 'Qualidade', 18),
  ('SIS_INF', 'Sistemas de Informação', 19),
  ('SUS', 'Sustentabilidade', 20)
) as d(disciplina_id, name, ordem)
on conflict (disciplina_id) do update
  set familia_id = excluded.familia_id, name = excluded.name, ordem = excluded.ordem, ativo = true;

insert into taxonomia.assuntos (assunto_id, disciplina_id, familia_id, name, ordem, ativo)
values
  ('ECO_01', 'ECO', 'ENGPRO', 'Macroeconomia', 1, true),
  ('ECO_02', 'ECO', 'ENGPRO', 'Microeconomia', 2, true),
  ('ENG_MET_01', 'ENG_MET', 'ENGPRO', 'Estudo e Padronização de Métodos', 1, true),
  ('ENG_MET_02', 'ENG_MET', 'ENGPRO', 'Mensuração do Trabalho', 2, true),
  ('ENG_PRO_01', 'ENG_PRO', 'ENGPRO', 'Arquitetura e Projeto do Produto', 1, true),
  ('ENG_PRO_02', 'ENG_PRO', 'ENGPRO', 'Integração do Desenvolvimento', 2, true),
  ('ENG_PRO_03', 'ENG_PRO', 'ENGPRO', 'Processo de Desenvolvimento de Produtos', 3, true),
  ('ENG_PRO_04', 'ENG_PRO', 'ENGPRO', 'Validação e Engenharia Reversa', 4, true),
  ('ENG_TRAB_01', 'ENG_TRAB', 'ENGPRO', 'Higiene, Segurança e Riscos Ocupacionais', 1, true),
  ('ENG_TRAB_02', 'ENG_TRAB', 'ENGPRO', 'Projeto do Trabalho', 2, true),
  ('ERG_01', 'ERG', 'ENGPRO', 'Análise e Projeto Ergonômico', 1, true),
  ('ERG_02', 'ERG', 'ENGPRO', 'Fundamentos de Ergonomia', 2, true),
  ('GES_INO_01', 'GES_INO', 'ENGPRO', 'Fundamentos, Estratégia e Métodos de Inovação', 1, true),
  ('GES_INO_02', 'GES_INO', 'ENGPRO', 'Gestão da Tecnologia', 2, true),
  ('GES_CUS_01', 'GES_CUS', 'ENGPRO', 'Análise Custo-Volume-Lucro e Custos para Decisão', 1, true),
  ('GES_CUS_02', 'GES_CUS', 'ENGPRO', 'Contabilidade de Custos', 2, true),
  ('GES_OPE_01', 'GES_OPE', 'ENGPRO', 'Estratégia de Operações', 1, true),
  ('GES_OPE_02', 'GES_OPE', 'ENGPRO', 'Localização e Arranjo Físico', 2, true),
  ('GES_OPE_03', 'GES_OPE', 'ENGPRO', 'Manufatura e Automação', 3, true),
  ('GES_OPE_04', 'GES_OPE', 'ENGPRO', 'Medição de Desempenho de Operações', 4, true),
  ('GES_OPE_05', 'GES_OPE', 'ENGPRO', 'Processos e Sistemas Produtivos', 5, true),
  ('GES_OPE_06', 'GES_OPE', 'ENGPRO', 'Produção Enxuta e Just in Time', 6, true),
  ('GES_PES_01', 'GES_PES', 'ENGPRO', 'Comportamento e Desenvolvimento de Pessoas', 1, true),
  ('GES_PES_02', 'GES_PES', 'ENGPRO', 'Planejamento e Provimento de Pessoas', 2, true),
  ('GES_PROJ_01', 'GES_PROJ', 'ENGPRO', 'Áreas de Gerenciamento', 1, true),
  ('GES_PROJ_02', 'GES_PROJ', 'ENGPRO', 'Cronograma e Redes', 2, true),
  ('GES_PROJ_03', 'GES_PROJ', 'ENGPRO', 'Fundamentos de Projetos', 3, true),
  ('GES_PROJ_04', 'GES_PROJ', 'ENGPRO', 'Governança de Projetos', 4, true),
  ('GES_PROJ_05', 'GES_PROJ', 'ENGPRO', 'Integração, Iniciação e Controle', 5, true),
  ('GES_PROJ_06', 'GES_PROJ', 'ENGPRO', 'Métodos Ágeis e Visuais', 6, true),
  ('GES_EST_01', 'GES_EST', 'ENGPRO', 'Análise Estratégica', 1, true),
  ('GES_EST_02', 'GES_EST', 'ENGPRO', 'Formulação Estratégica', 2, true),
  ('GES_EST_03', 'GES_EST', 'ENGPRO', 'Implementação Estratégica', 3, true),
  ('GES_EST_04', 'GES_EST', 'ENGPRO', 'Marketing', 4, true),
  ('GES_FIN_01', 'GES_FIN', 'ENGPRO', 'Finanças Corporativas', 1, true),
  ('GES_FIN_02', 'GES_FIN', 'ENGPRO', 'Mercados, Risco e Retorno', 2, true),
  ('GES_ORG_01', 'GES_ORG', 'ENGPRO', 'Decisão e Conhecimento Organizacional', 1, true),
  ('GES_ORG_02', 'GES_ORG', 'ENGPRO', 'Gestão por Processos', 2, true),
  ('GES_ORG_03', 'GES_ORG', 'ENGPRO', 'Organização, Governança e Desempenho', 3, true),
  ('LOG_CAD_01', 'LOG_CAD', 'ENGPRO', 'Armazenagem e Movimentação', 1, true),
  ('LOG_CAD_02', 'LOG_CAD', 'ENGPRO', 'Distribuição e Transportes', 2, true),
  ('LOG_CAD_03', 'LOG_CAD', 'ENGPRO', 'Fundamentos, Nível de Serviço e Operadores', 3, true),
  ('LOG_CAD_04', 'LOG_CAD', 'ENGPRO', 'Gestão da Cadeia de Suprimentos', 4, true),
  ('LOG_CAD_05', 'LOG_CAD', 'ENGPRO', 'Gestão de Estoques', 5, true),
  ('LOG_CAD_06', 'LOG_CAD', 'ENGPRO', 'Tecnologias Logísticas', 6, true),
  ('MAN_CONF_01', 'MAN_CONF', 'ENGPRO', 'Confiabilidade: Fundamentos, Sistemas e Indicadores', 1, true),
  ('MAN_CONF_02', 'MAN_CONF', 'ENGPRO', 'Estratégias de Manutenção', 2, true),
  ('MAN_CONF_03', 'MAN_CONF', 'ENGPRO', 'Gestão da Manutenção', 3, true),
  ('PES_OP_01', 'PES_OP', 'ENGPRO', 'Apoio à Decisão', 1, true),
  ('PES_OP_02', 'PES_OP', 'ENGPRO', 'Fundamentos, Simulação e Processos Estocásticos', 2, true),
  ('PES_OP_03', 'PES_OP', 'ENGPRO', 'Otimização Discreta e em Redes', 3, true),
  ('PES_OP_04', 'PES_OP', 'ENGPRO', 'Programação Linear e Não Linear', 4, true),
  ('PCP_01', 'PCP', 'ENGPRO', 'Planejamento Agregado e da Capacidade', 1, true),
  ('PCP_02', 'PCP', 'ENGPRO', 'Plano Mestre e Necessidades de Materiais', 2, true),
  ('PCP_03', 'PCP', 'ENGPRO', 'Previsão de Demanda', 3, true),
  ('PCP_04', 'PCP', 'ENGPRO', 'Programação, Balanceamento e Restrições', 4, true),
  ('PCP_05', 'PCP', 'ENGPRO', 'Sistemas de PCP', 5, true),
  ('QUA_01', 'QUA', 'ENGPRO', 'Ferramentas da Qualidade', 1, true),
  ('QUA_02', 'QUA', 'ENGPRO', 'Fundamentos da Qualidade', 2, true),
  ('QUA_03', 'QUA', 'ENGPRO', 'Gestão da Qualidade Total', 3, true),
  ('QUA_04', 'QUA', 'ENGPRO', 'Melhoria e Padronização', 4, true),
  ('QUA_05', 'QUA', 'ENGPRO', 'Planejamento e Controle da Qualidade', 5, true),
  ('SIS_INF_01', 'SIS_INF', 'ENGPRO', 'Gestão e Infraestrutura da Informação', 1, true),
  ('SIS_INF_02', 'SIS_INF', 'ENGPRO', 'Sistemas Gerenciais e Integrados', 2, true),
  ('SUS_01', 'SUS', 'ENGPRO', 'Gestão Ambiental', 1, true),
  ('SUS_02', 'SUS', 'ENGPRO', 'Produção Sustentável', 2, true),
  ('SUS_03', 'SUS', 'ENGPRO', 'Resíduos e Poluição', 3, true)
on conflict (assunto_id) do update
  set disciplina_id = excluded.disciplina_id, familia_id = excluded.familia_id, name = excluded.name, ordem = excluded.ordem, ativo = true;

insert into taxonomia.subassuntos (subassunto_id, assunto_id, familia_id, name, ordem, ativo)
values
  ('ECO_01_001', 'ECO_01', 'ENGPRO', 'Ciclos, Produto e Renda', 1, true),
  ('ECO_01_002', 'ECO_01', 'ENGPRO', 'Comércio Internacional e Vantagens Comparativas', 2, true),
  ('ECO_01_003', 'ECO_01', 'ENGPRO', 'Inflação', 3, true),
  ('ECO_01_004', 'ECO_01', 'ENGPRO', 'Moeda e Preferência pela Liquidez', 4, true),
  ('ECO_01_005', 'ECO_01', 'ENGPRO', 'Políticas Fiscal e Monetária', 5, true),
  ('ECO_02_001', 'ECO_02', 'ENGPRO', 'Estruturas de Mercado e Regulação', 1, true),
  ('ECO_02_002', 'ECO_02', 'ENGPRO', 'Oferta, Demanda e Elasticidade', 2, true),
  ('ECO_02_003', 'ECO_02', 'ENGPRO', 'Teoria da Firma: Produção, Custos e Escala', 3, true),
  ('ENG_MET_01_001', 'ENG_MET_01', 'ENGPRO', 'Economia de Movimentos, Therbligs e Diagrama Bimanual', 1, true),
  ('ENG_MET_01_002', 'ENG_MET_01', 'ENGPRO', 'Fluxogramas e Mapeamento de Processos (ASME)', 2, true),
  ('ENG_MET_01_003', 'ENG_MET_01', 'ENGPRO', 'Melhoria do Método de Trabalho', 3, true),
  ('ENG_MET_01_004', 'ENG_MET_01', 'ENGPRO', 'Padronização e Estabilização', 4, true),
  ('ENG_MET_02_001', 'ENG_MET_02', 'ENGPRO', 'Amostragem do Trabalho', 1, true),
  ('ENG_MET_02_002', 'ENG_MET_02', 'ENGPRO', 'Cronometragem e Tempos-Padrão', 2, true),
  ('ENG_MET_02_003', 'ENG_MET_02', 'ENGPRO', 'Curva de Aprendizagem', 3, true),
  ('ENG_MET_02_004', 'ENG_MET_02', 'ENGPRO', 'Tempos Predeterminados (MTM)', 4, true),
  ('ENG_PRO_01_001', 'ENG_PRO_01', 'ENGPRO', 'Arquitetura e Modularidade', 1, true),
  ('ENG_PRO_01_002', 'ENG_PRO_01', 'ENGPRO', 'Design for X (DFX): Ecodesign e Desmontagem', 2, true),
  ('ENG_PRO_01_003', 'ENG_PRO_01', 'ENGPRO', 'Projeto de Embalagens', 3, true),
  ('ENG_PRO_02_001', 'ENG_PRO_02', 'ENGPRO', 'CAD/CAM/CAE no Desenvolvimento', 1, true),
  ('ENG_PRO_02_002', 'ENG_PRO_02', 'ENGPRO', 'Engenharia Simultânea e Equipes', 2, true),
  ('ENG_PRO_03_001', 'ENG_PRO_03', 'ENGPRO', 'Casa da Qualidade e Requisitos (QFD)', 1, true),
  ('ENG_PRO_03_002', 'ENG_PRO_03', 'ENGPRO', 'Ciclo de Vida do Produto', 2, true),
  ('ENG_PRO_03_003', 'ENG_PRO_03', 'ENGPRO', 'Metodologia de Projeto e Matriz Morfológica', 3, true),
  ('ENG_PRO_03_004', 'ENG_PRO_03', 'ENGPRO', 'Modelos e Fases do PDP', 4, true),
  ('ENG_PRO_03_005', 'ENG_PRO_03', 'ENGPRO', 'Planejamento e Viabilidade', 5, true),
  ('ENG_PRO_03_006', 'ENG_PRO_03', 'ENGPRO', 'Projeto Conceitual e Seleção de Conceitos', 6, true),
  ('ENG_PRO_03_007', 'ENG_PRO_03', 'ENGPRO', 'Projeto Informacional', 7, true),
  ('ENG_PRO_03_008', 'ENG_PRO_03', 'ENGPRO', 'Projeto Preliminar e Detalhado', 8, true),
  ('ENG_PRO_04_001', 'ENG_PRO_04', 'ENGPRO', 'Engenharia Reversa', 1, true),
  ('ENG_PRO_04_002', 'ENG_PRO_04', 'ENGPRO', 'Prototipagem e Testes', 2, true),
  ('ENG_TRAB_01_001', 'ENG_TRAB_01', 'ENGPRO', 'Acidentes do Trabalho e Prevenção', 1, true),
  ('ENG_TRAB_01_002', 'ENG_TRAB_01', 'ENGPRO', 'Agentes Físicos Ocupacionais', 2, true),
  ('ENG_TRAB_01_003', 'ENG_TRAB_01', 'ENGPRO', 'Análise e Mapeamento de Riscos', 3, true),
  ('ENG_TRAB_01_004', 'ENG_TRAB_01', 'ENGPRO', 'EPI e Proteção Respiratória', 4, true),
  ('ENG_TRAB_01_005', 'ENG_TRAB_01', 'ENGPRO', 'Sistemas de Gestão de SST', 5, true),
  ('ENG_TRAB_02_001', 'ENG_TRAB_02', 'ENGPRO', 'Condições e Jornada de Trabalho', 1, true),
  ('ENG_TRAB_02_002', 'ENG_TRAB_02', 'ENGPRO', 'Desenho de Cargos e Enriquecimento do Trabalho', 2, true),
  ('ENG_TRAB_02_003', 'ENG_TRAB_02', 'ENGPRO', 'Organização e Controle do Trabalho', 3, true),
  ('ERG_01_001', 'ERG_01', 'ENGPRO', 'AET e Integração com Métodos', 1, true),
  ('ERG_01_002', 'ERG_01', 'ENGPRO', 'Antropometria, Postura e Postos de Trabalho', 2, true),
  ('ERG_01_003', 'ERG_01', 'ENGPRO', 'Conforto Ambiental e Ergonomia Visual', 3, true),
  ('ERG_02_001', 'ERG_02', 'ENGPRO', 'Conceitos, Domínios e Classificação da Ergonomia', 1, true),
  ('GES_INO_01_001', 'GES_INO_01', 'ENGPRO', 'Ambidestria, Risco e Incerteza', 1, true),
  ('GES_INO_01_002', 'GES_INO_01', 'ENGPRO', 'Ambiente e Sistemas de Inovação', 2, true),
  ('GES_INO_01_003', 'GES_INO_01', 'ENGPRO', 'Design Thinking e Métodos de Ideação', 3, true),
  ('GES_INO_01_004', 'GES_INO_01', 'ENGPRO', 'Modelos e Processo de Inovação', 4, true),
  ('GES_INO_01_005', 'GES_INO_01', 'ENGPRO', 'Tipos e Graus de Inovação', 5, true),
  ('GES_INO_02_001', 'GES_INO_02', 'ENGPRO', 'Aquisição de Tecnologia', 1, true),
  ('GES_INO_02_002', 'GES_INO_02', 'ENGPRO', 'Organização de P&D', 2, true),
  ('GES_CUS_01_001', 'GES_CUS_01', 'ENGPRO', 'Custos de Oportunidade e Custos Afundados', 1, true),
  ('GES_CUS_01_002', 'GES_CUS_01', 'ENGPRO', 'Formação de Preços', 2, true),
  ('GES_CUS_01_003', 'GES_CUS_01', 'ENGPRO', 'Margens e Ponto de Equilíbrio', 3, true),
  ('GES_CUS_02_001', 'GES_CUS_02', 'ENGPRO', 'Classificação de Custos', 1, true),
  ('GES_CUS_02_002', 'GES_CUS_02', 'ENGPRO', 'CMV e Resultado Operacional', 2, true),
  ('GES_CUS_02_003', 'GES_CUS_02', 'ENGPRO', 'Custos Unitários e Apropriação', 3, true),
  ('GES_CUS_02_004', 'GES_CUS_02', 'ENGPRO', 'Estimativa de Custos e Fator de Escala', 4, true),
  ('GES_CUS_02_005', 'GES_CUS_02', 'ENGPRO', 'Métodos de Custeio', 5, true),
  ('GES_OPE_01_001', 'GES_OPE_01', 'ENGPRO', 'Estrutura e Infraestrutura', 1, true),
  ('GES_OPE_01_002', 'GES_OPE_01', 'ENGPRO', 'Formulação e Alinhamento', 2, true),
  ('GES_OPE_01_003', 'GES_OPE_01', 'ENGPRO', 'Prioridades Competitivas e Matriz de Desempenho', 3, true),
  ('GES_OPE_02_001', 'GES_OPE_02', 'ENGPRO', 'Critérios de Localização', 1, true),
  ('GES_OPE_02_002', 'GES_OPE_02', 'ENGPRO', 'Modelos de Localização', 2, true),
  ('GES_OPE_02_003', 'GES_OPE_02', 'ENGPRO', 'Tipos de Arranjo Físico', 3, true),
  ('GES_OPE_03_001', 'GES_OPE_03', 'ENGPRO', 'Indústria 4.0 e IoT Industrial', 1, true),
  ('GES_OPE_03_002', 'GES_OPE_03', 'ENGPRO', 'Integração CAD/CAM e CNC', 2, true),
  ('GES_OPE_03_003', 'GES_OPE_03', 'ENGPRO', 'Manufatura Integrada (CIM)', 3, true),
  ('GES_OPE_03_004', 'GES_OPE_03', 'ENGPRO', 'Sistemas Flexíveis e Células', 4, true),
  ('GES_OPE_04_001', 'GES_OPE_04', 'ENGPRO', 'Capacidade, Utilização e Eficiência', 1, true),
  ('GES_OPE_04_002', 'GES_OPE_04', 'ENGPRO', 'Lei de Little, Fluxo e Lead Time', 2, true),
  ('GES_OPE_04_003', 'GES_OPE_04', 'ENGPRO', 'Produtividade e Indicadores Operacionais', 3, true),
  ('GES_OPE_05_001', 'GES_OPE_05', 'ENGPRO', 'Estratégias de Atendimento à Demanda (MTS/MTO/ATO)', 1, true),
  ('GES_OPE_05_002', 'GES_OPE_05', 'ENGPRO', 'Paradigmas de Manufatura', 2, true),
  ('GES_OPE_05_003', 'GES_OPE_05', 'ENGPRO', 'Projeto de Serviços', 3, true),
  ('GES_OPE_05_004', 'GES_OPE_05', 'ENGPRO', 'Tipologia e Fluxos de Processos', 4, true),
  ('GES_OPE_06_001', 'GES_OPE_06', 'ENGPRO', 'Princípios e Desperdícios Lean/JIT', 1, true),
  ('GES_OPE_06_002', 'GES_OPE_06', 'ENGPRO', 'Produção Puxada e Kanban', 2, true),
  ('GES_OPE_06_003', 'GES_OPE_06', 'ENGPRO', 'Trabalho Padronizado, SMED e Poka-Yoke', 3, true),
  ('GES_PES_01_001', 'GES_PES_01', 'ENGPRO', 'Avaliação de Desempenho e Remuneração', 1, true),
  ('GES_PES_01_002', 'GES_PES_01', 'ENGPRO', 'Equipes e Trabalho Autodirigido', 2, true),
  ('GES_PES_01_003', 'GES_PES_01', 'ENGPRO', 'Motivação e Liderança', 3, true),
  ('GES_PES_01_004', 'GES_PES_01', 'ENGPRO', 'Treinamento e Desenvolvimento', 4, true),
  ('GES_PES_02_001', 'GES_PES_02', 'ENGPRO', 'Planejamento da Força de Trabalho e Indicadores', 1, true),
  ('GES_PES_02_002', 'GES_PES_02', 'ENGPRO', 'Recrutamento e Seleção', 2, true),
  ('GES_PROJ_01_001', 'GES_PROJ_01', 'ENGPRO', 'Aquisições e Contratos', 1, true),
  ('GES_PROJ_01_002', 'GES_PROJ_01', 'ENGPRO', 'Comunicação e Partes Interessadas', 2, true),
  ('GES_PROJ_01_003', 'GES_PROJ_01', 'ENGPRO', 'Custos do Projeto', 3, true),
  ('GES_PROJ_01_004', 'GES_PROJ_01', 'ENGPRO', 'Escopo do Projeto', 4, true),
  ('GES_PROJ_01_005', 'GES_PROJ_01', 'ENGPRO', 'Qualidade do Projeto', 5, true),
  ('GES_PROJ_01_006', 'GES_PROJ_01', 'ENGPRO', 'Recursos do Projeto', 6, true),
  ('GES_PROJ_01_007', 'GES_PROJ_01', 'ENGPRO', 'Riscos do Projeto', 7, true),
  ('GES_PROJ_02_001', 'GES_PROJ_02', 'ENGPRO', 'Compressão de Cronograma', 1, true),
  ('GES_PROJ_02_002', 'GES_PROJ_02', 'ENGPRO', 'PERT Probabilístico', 2, true),
  ('GES_PROJ_02_003', 'GES_PROJ_02', 'ENGPRO', 'Redes, Caminho Crítico e Folgas', 3, true),
  ('GES_PROJ_03_001', 'GES_PROJ_03', 'ENGPRO', 'Conceitos e Ciclo de Vida', 1, true),
  ('GES_PROJ_03_002', 'GES_PROJ_03', 'ENGPRO', 'Grupos de Processos e Referenciais', 2, true),
  ('GES_PROJ_03_003', 'GES_PROJ_03', 'ENGPRO', 'Tripla Restrição', 3, true),
  ('GES_PROJ_04_001', 'GES_PROJ_04', 'ENGPRO', 'Estruturas e Maturidade', 1, true),
  ('GES_PROJ_04_002', 'GES_PROJ_04', 'ENGPRO', 'Portfólio e Priorização', 2, true),
  ('GES_PROJ_05_001', 'GES_PROJ_05', 'ENGPRO', 'Indicadores e Valor Agregado', 1, true),
  ('GES_PROJ_05_002', 'GES_PROJ_05', 'ENGPRO', 'Planejamento e Controle Integrados', 2, true),
  ('GES_PROJ_05_003', 'GES_PROJ_05', 'ENGPRO', 'Termo de Abertura', 3, true),
  ('GES_PROJ_06_001', 'GES_PROJ_06', 'ENGPRO', 'Métodos Ágeis, Scrum e Quadro Kanban', 1, true),
  ('GES_PROJ_06_002', 'GES_PROJ_06', 'ENGPRO', 'Project Model Canvas', 2, true),
  ('GES_EST_01_001', 'GES_EST_01', 'ENGPRO', 'Análise Setorial, Cinco Forças e Cadeia de Valor', 1, true),
  ('GES_EST_01_002', 'GES_EST_01', 'ENGPRO', 'Crescimento e Portfólio', 2, true),
  ('GES_EST_01_003', 'GES_EST_01', 'ENGPRO', 'Estratégias Genéricas e Vantagem Competitiva', 3, true),
  ('GES_EST_01_004', 'GES_EST_01', 'ENGPRO', 'Recursos, Competências e VBR', 4, true),
  ('GES_EST_02_001', 'GES_EST_02', 'ENGPRO', 'Diagnóstico Estratégico', 1, true),
  ('GES_EST_02_002', 'GES_EST_02', 'ENGPRO', 'Escolas e Níveis de Estratégia', 2, true),
  ('GES_EST_02_003', 'GES_EST_02', 'ENGPRO', 'Missão, Visão e Identidade', 3, true),
  ('GES_EST_03_001', 'GES_EST_03', 'ENGPRO', 'BSC, Mapas Estratégicos e Medição de Desempenho', 1, true),
  ('GES_EST_03_002', 'GES_EST_03', 'ENGPRO', 'Desdobramento de Diretrizes (Hoshin Kanri)', 2, true),
  ('GES_EST_04_001', 'GES_EST_04', 'ENGPRO', 'Comportamento e Segmentação', 1, true),
  ('GES_EST_04_002', 'GES_EST_04', 'ENGPRO', 'Composto de Marketing (4 Ps)', 2, true),
  ('GES_EST_04_003', 'GES_EST_04', 'ENGPRO', 'Planejamento e Estratégias de Marketing', 3, true),
  ('GES_FIN_01_001', 'GES_FIN_01', 'ENGPRO', 'Alavancagem', 1, true),
  ('GES_FIN_01_002', 'GES_FIN_01', 'ENGPRO', 'Custo de Capital e Criação de Valor', 2, true),
  ('GES_FIN_01_003', 'GES_FIN_01', 'ENGPRO', 'Demonstrações e Indicadores', 3, true),
  ('GES_FIN_02_001', 'GES_FIN_02', 'ENGPRO', 'CAPM e Risco Sistemático', 1, true),
  ('GES_FIN_02_002', 'GES_FIN_02', 'ENGPRO', 'Desempenho Ajustado ao Risco', 2, true),
  ('GES_FIN_02_003', 'GES_FIN_02', 'ENGPRO', 'Hedge e Correlação', 3, true),
  ('GES_FIN_02_004', 'GES_FIN_02', 'ENGPRO', 'Mercados e Curva de Juros', 4, true),
  ('GES_FIN_02_005', 'GES_FIN_02', 'ENGPRO', 'Simulação de Risco', 5, true),
  ('GES_ORG_01_001', 'GES_ORG_01', 'ENGPRO', 'Gestão do Conhecimento e Inteligência Competitiva', 1, true),
  ('GES_ORG_01_002', 'GES_ORG_01', 'ENGPRO', 'Processo Decisório e Decisão em Grupo', 2, true),
  ('GES_ORG_01_003', 'GES_ORG_01', 'ENGPRO', 'Racionalidade e Vieses', 3, true),
  ('GES_ORG_02_001', 'GES_ORG_02', 'ENGPRO', 'BPM e Automação', 1, true),
  ('GES_ORG_02_002', 'GES_ORG_02', 'ENGPRO', 'Mapeamento, Interfaces e Handoffs', 2, true),
  ('GES_ORG_02_003', 'GES_ORG_02', 'ENGPRO', 'Redesenho e Reengenharia', 3, true),
  ('GES_ORG_03_001', 'GES_ORG_03', 'ENGPRO', 'Controle Organizacional e Níveis de Planejamento', 1, true),
  ('GES_ORG_03_002', 'GES_ORG_03', 'ENGPRO', 'Empreendedorismo e Plano de Negócios', 2, true),
  ('GES_ORG_03_003', 'GES_ORG_03', 'ENGPRO', 'Estruturas e Mintzberg', 3, true),
  ('GES_ORG_03_004', 'GES_ORG_03', 'ENGPRO', 'Governança Corporativa, Ética e Compliance', 4, true),
  ('GES_ORG_03_005', 'GES_ORG_03', 'ENGPRO', 'Mudança Organizacional', 5, true),
  ('LOG_CAD_01_001', 'LOG_CAD_01', 'ENGPRO', 'Decisões de Armazenagem', 1, true),
  ('LOG_CAD_01_002', 'LOG_CAD_01', 'ENGPRO', 'Movimentação, Unitização e Embalagem', 2, true),
  ('LOG_CAD_02_001', 'LOG_CAD_02', 'ENGPRO', 'Canais e Modais', 1, true),
  ('LOG_CAD_02_002', 'LOG_CAD_02', 'ENGPRO', 'Fluxos Reversos', 2, true),
  ('LOG_CAD_02_003', 'LOG_CAD_02', 'ENGPRO', 'Redes e Configurações Logísticas', 3, true),
  ('LOG_CAD_03_001', 'LOG_CAD_03', 'ENGPRO', 'Atividades e Estratégia Logística', 1, true),
  ('LOG_CAD_03_002', 'LOG_CAD_03', 'ENGPRO', 'Disponibilidade e Trade-offs', 2, true),
  ('LOG_CAD_03_003', 'LOG_CAD_03', 'ENGPRO', 'Operadores Logísticos e 4PL', 3, true),
  ('LOG_CAD_04_001', 'LOG_CAD_04', 'ENGPRO', 'Compras, Fornecedores e Negociação', 1, true),
  ('LOG_CAD_04_002', 'LOG_CAD_04', 'ENGPRO', 'Integração da Cadeia de Suprimentos', 2, true),
  ('LOG_CAD_04_003', 'LOG_CAD_04', 'ENGPRO', 'Reposição Colaborativa (CR/VMI)', 3, true),
  ('LOG_CAD_05_001', 'LOG_CAD_05', 'ENGPRO', 'Classificação ABC e Tipos de Estoque', 1, true),
  ('LOG_CAD_05_002', 'LOG_CAD_05', 'ENGPRO', 'Custos e Indicadores de Estoque', 2, true),
  ('LOG_CAD_05_003', 'LOG_CAD_05', 'ENGPRO', 'Lote Econômico de Compra', 3, true),
  ('LOG_CAD_05_004', 'LOG_CAD_05', 'ENGPRO', 'Reposição e Ponto de Pedido', 4, true),
  ('LOG_CAD_06_001', 'LOG_CAD_06', 'ENGPRO', 'EDI e Integração de Dados', 1, true),
  ('LOG_CAD_06_002', 'LOG_CAD_06', 'ENGPRO', 'Identificação e Rastreabilidade', 2, true),
  ('MAN_CONF_01_001', 'MAN_CONF_01', 'ENGPRO', 'Confiabilidade e Taxa de Falhas', 1, true),
  ('MAN_CONF_01_002', 'MAN_CONF_01', 'ENGPRO', 'Disponibilidade, MTBF e MTTR', 2, true),
  ('MAN_CONF_01_003', 'MAN_CONF_01', 'ENGPRO', 'Série, Paralelo e Standby', 3, true),
  ('MAN_CONF_02_001', 'MAN_CONF_02', 'ENGPRO', 'Tipos e Monitoramento de Condição', 1, true),
  ('MAN_CONF_02_002', 'MAN_CONF_02', 'ENGPRO', 'TPM e Manutenção Autônoma', 2, true),
  ('MAN_CONF_03_001', 'MAN_CONF_03', 'ENGPRO', 'Organização e Manutenibilidade', 1, true),
  ('MAN_CONF_03_002', 'MAN_CONF_03', 'ENGPRO', 'Planejamento e Controle', 2, true),
  ('PES_OP_01_001', 'PES_OP_01', 'ENGPRO', 'Análise Envoltória de Dados (DEA)', 1, true),
  ('PES_OP_01_002', 'PES_OP_01', 'ENGPRO', 'Apoio Multicritério à Decisão (AHP)', 2, true),
  ('PES_OP_01_003', 'PES_OP_01', 'ENGPRO', 'Decisão sob Incerteza', 3, true),
  ('PES_OP_01_004', 'PES_OP_01', 'ENGPRO', 'Risco, Valor Esperado e Utilidade', 4, true),
  ('PES_OP_01_005', 'PES_OP_01', 'ENGPRO', 'Teoria dos Jogos e Equilíbrio', 5, true),
  ('PES_OP_02_001', 'PES_OP_02', 'ENGPRO', 'Cadeias de Markov', 1, true),
  ('PES_OP_02_002', 'PES_OP_02', 'ENGPRO', 'Eventos Discretos e Monte Carlo', 2, true),
  ('PES_OP_02_003', 'PES_OP_02', 'ENGPRO', 'Metodologia e Fases da PO', 3, true),
  ('PES_OP_02_004', 'PES_OP_02', 'ENGPRO', 'Modelos e Desempenho de Filas', 4, true),
  ('PES_OP_03_001', 'PES_OP_03', 'ENGPRO', 'Otimização Combinatória e Heurísticas', 1, true),
  ('PES_OP_03_002', 'PES_OP_03', 'ENGPRO', 'Redes, Transporte e Roteirização', 2, true),
  ('PES_OP_04_001', 'PES_OP_04', 'ENGPRO', 'Formulação e Modelagem', 1, true),
  ('PES_OP_04_002', 'PES_OP_04', 'ENGPRO', 'Método Simplex', 2, true),
  ('PES_OP_04_003', 'PES_OP_04', 'ENGPRO', 'Programação Não Linear', 3, true),
  ('PES_OP_04_004', 'PES_OP_04', 'ENGPRO', 'Sensibilidade e Dualidade', 4, true),
  ('PES_OP_04_005', 'PES_OP_04', 'ENGPRO', 'Solução Gráfica', 5, true),
  ('PCP_01_001', 'PCP_01', 'ENGPRO', 'Estratégias de Capacidade', 1, true),
  ('PCP_01_002', 'PCP_01', 'ENGPRO', 'Estratégias de Planejamento Agregado', 2, true),
  ('PCP_01_003', 'PCP_01', 'ENGPRO', 'Planejamento da Capacidade e CRP', 3, true),
  ('PCP_02_001', 'PCP_02', 'ENGPRO', 'Estrutura do Produto (BOM) e Cálculo de Necessidades', 1, true),
  ('PCP_02_002', 'PCP_02', 'ENGPRO', 'MPS: Estrutura e Viabilidade', 2, true),
  ('PCP_02_003', 'PCP_02', 'ENGPRO', 'MRP e MRP II', 3, true),
  ('PCP_03_001', 'PCP_03', 'ENGPRO', 'Gestão da Demanda', 1, true),
  ('PCP_03_002', 'PCP_03', 'ENGPRO', 'Métodos de Séries Temporais', 2, true),
  ('PCP_03_003', 'PCP_03', 'ENGPRO', 'Métodos Qualitativos', 3, true),
  ('PCP_03_004', 'PCP_03', 'ENGPRO', 'Modelos Causais', 4, true),
  ('PCP_04_001', 'PCP_04', 'ENGPRO', 'Balanceamento de Linha: Tempo de Ciclo e Postos', 1, true),
  ('PCP_04_002', 'PCP_04', 'ENGPRO', 'Carregamento e Sequenciamento', 2, true),
  ('PCP_04_003', 'PCP_04', 'ENGPRO', 'Gargalos e Tambor-Pulmão-Corda (TOC)', 3, true),
  ('PCP_05_001', 'PCP_05', 'ENGPRO', 'Controle e Acompanhamento da Produção', 1, true),
  ('PCP_05_002', 'PCP_05', 'ENGPRO', 'Níveis de Planejamento', 2, true),
  ('PCP_05_003', 'PCP_05', 'ENGPRO', 'Sistemas APS e Integração MRP/ERP no PCP', 3, true),
  ('QUA_01_001', 'QUA_01', 'ENGPRO', 'Análise de Falhas e Causa Raiz (FMEA, FTA, 5 Porquês)', 1, true),
  ('QUA_01_002', 'QUA_01', 'ENGPRO', 'Ferramentas Básicas', 2, true),
  ('QUA_01_003', 'QUA_01', 'ENGPRO', 'Ferramentas Gerenciais', 3, true),
  ('QUA_02_001', 'QUA_02', 'ENGPRO', 'Conceitos e Dimensões da Qualidade', 1, true),
  ('QUA_02_002', 'QUA_02', 'ENGPRO', 'Gurus e Filosofias', 2, true),
  ('QUA_02_003', 'QUA_02', 'ENGPRO', 'Qualidade em Serviços', 3, true),
  ('QUA_03_001', 'QUA_03', 'ENGPRO', 'Cliente, Pessoas e Organização', 1, true),
  ('QUA_03_002', 'QUA_03', 'ENGPRO', 'Modelos de Excelência (MEG)', 2, true),
  ('QUA_03_003', 'QUA_03', 'ENGPRO', 'Princípios da GQT', 3, true),
  ('QUA_04_001', 'QUA_04', 'ENGPRO', '5S', 1, true),
  ('QUA_04_002', 'QUA_04', 'ENGPRO', 'Benchmarking', 2, true),
  ('QUA_04_003', 'QUA_04', 'ENGPRO', 'Padronização e Procedimentos', 3, true),
  ('QUA_04_004', 'QUA_04', 'ENGPRO', 'PDCA e Melhoria Contínua', 4, true),
  ('QUA_04_005', 'QUA_04', 'ENGPRO', 'Seis Sigma e DMAIC', 5, true),
  ('QUA_05_001', 'QUA_05', 'ENGPRO', 'Controle Estatístico de Processo (CEP) e Capacidade', 1, true),
  ('QUA_05_002', 'QUA_05', 'ENGPRO', 'Custos da Qualidade', 2, true),
  ('QUA_05_003', 'QUA_05', 'ENGPRO', 'Inspeção, Amostragem de Aceitação e Não Conformidades', 3, true),
  ('QUA_05_004', 'QUA_05', 'ENGPRO', 'Planejamento da Qualidade', 4, true),
  ('QUA_05_005', 'QUA_05', 'ENGPRO', 'Qualidade de Fornecedores', 5, true),
  ('QUA_05_006', 'QUA_05', 'ENGPRO', 'Sistemas de Gestão da Qualidade e ISO 9000', 6, true),
  ('SIS_INF_01_001', 'SIS_INF_01', 'ENGPRO', 'Computação em Nuvem e SaaS', 1, true),
  ('SIS_INF_01_002', 'SIS_INF_01', 'ENGPRO', 'Estratégia, TI e Recursos Informacionais', 2, true),
  ('SIS_INF_02_001', 'SIS_INF_02', 'ENGPRO', 'ERP: Módulos, Arquitetura e Implantação', 1, true),
  ('SIS_INF_02_002', 'SIS_INF_02', 'ENGPRO', 'Sistemas de Apoio à Decisão (SAD)', 2, true),
  ('SIS_INF_02_003', 'SIS_INF_02', 'ENGPRO', 'Sistemas de Informação Gerencial (SIG) e Níveis Decisórios', 3, true),
  ('SUS_01_001', 'SUS_01', 'ENGPRO', 'Desenvolvimento Sustentável, TBL e Responsabilidade Social', 1, true),
  ('SUS_01_002', 'SUS_01', 'ENGPRO', 'Gestão Ambiental Empresarial e Práticas Sustentáveis', 2, true),
  ('SUS_01_003', 'SUS_01', 'ENGPRO', 'Gestão de Carbono e REDD', 3, true),
  ('SUS_01_004', 'SUS_01', 'ENGPRO', 'Licenciamento e Avaliação de Impacto Ambiental', 4, true),
  ('SUS_01_005', 'SUS_01', 'ENGPRO', 'Sistemas de Gestão Ambiental (ISO 14001)', 5, true),
  ('SUS_02_001', 'SUS_02', 'ENGPRO', 'Avaliação do Ciclo de Vida', 1, true),
  ('SUS_02_002', 'SUS_02', 'ENGPRO', 'Matriz e Eficiência Energética', 2, true),
  ('SUS_02_003', 'SUS_02', 'ENGPRO', 'Produção Limpa e Ecoeficiência', 3, true),
  ('SUS_03_001', 'SUS_03', 'ENGPRO', 'Controle da Poluição Industrial', 1, true),
  ('SUS_03_002', 'SUS_03', 'ENGPRO', 'Gestão de Resíduos Sólidos e Rejeitos', 2, true),
  ('SUS_03_003', 'SUS_03', 'ENGPRO', 'Tratamento e Reuso de Efluentes', 3, true)
on conflict (subassunto_id) do update
  set assunto_id = excluded.assunto_id, familia_id = excluded.familia_id, name = excluded.name, ordem = excluded.ordem, ativo = true;

commit;
