-- ============================================================================
-- ÁRVORE MESTRA — ENGENHARIA DE PRODUÇÃO
-- Gerado a partir de ENGENHARIA_PRODUCAO.md (Parte I). Idempotente: pode ser
-- reexecutado; usa ON CONFLICT (codigo) DO UPDATE.
--
-- Schema assumido (ajuste os nomes se o seu for diferente):
--   disciplinas (codigo PK, nome)
--   assuntos    (codigo PK, nome, disciplina_codigo FK -> disciplinas.codigo)
--   subassuntos (codigo PK, nome, assunto_codigo FK -> assuntos.codigo)
--
-- O bloco DDL abaixo só cria as tabelas se não existirem. Se o Núcleo Básico
-- já foi inserido em tabelas com outros nomes, remova o DDL e renomeie as
-- tabelas nos INSERTs.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS disciplinas (
  codigo text PRIMARY KEY,
  nome   text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS assuntos (
  codigo            text PRIMARY KEY,
  nome              text NOT NULL,
  disciplina_codigo text NOT NULL REFERENCES disciplinas(codigo),
  UNIQUE (disciplina_codigo, nome)
);

CREATE TABLE IF NOT EXISTS subassuntos (
  codigo         text PRIMARY KEY,
  nome           text NOT NULL,
  assunto_codigo text NOT NULL REFERENCES assuntos(codigo),
  UNIQUE (assunto_codigo, nome)
);

-- Disciplinas (20)
INSERT INTO disciplinas (codigo, nome) VALUES
  ('ECO', 'Economia'),
  ('ENG_MET', 'Engenharia de Métodos'),
  ('ENG_PRO', 'Engenharia do Produto'),
  ('ENG_TRAB', 'Engenharia do Trabalho'),
  ('ERG', 'Ergonomia'),
  ('GES_INO', 'Gestão da Inovação e Tecnologia'),
  ('GES_CUS', 'Gestão de Custos'),
  ('GES_OPE', 'Gestão de Operações'),
  ('GES_PES', 'Gestão de Pessoas'),
  ('GES_PROJ', 'Gestão de Projetos'),
  ('GES_EST', 'Gestão Estratégica'),
  ('GES_FIN', 'Gestão Financeira e Investimentos'),
  ('GES_ORG', 'Gestão Organizacional'),
  ('LOG_CAD', 'Logística e Cadeia de Suprimentos'),
  ('MAN_CONF', 'Manutenção e Confiabilidade'),
  ('PES_OP', 'Pesquisa Operacional'),
  ('PCP', 'Planejamento e Controle da Produção'),
  ('QUA', 'Qualidade'),
  ('SIS_INF', 'Sistemas de Informação'),
  ('SUS', 'Sustentabilidade')
ON CONFLICT (codigo) DO UPDATE SET nome = EXCLUDED.nome;

-- Assuntos (67)
INSERT INTO assuntos (codigo, nome, disciplina_codigo) VALUES
  ('ECO_01', 'Macroeconomia', 'ECO'),
  ('ECO_02', 'Microeconomia', 'ECO'),
  ('ENG_MET_01', 'Estudo e Padronização de Métodos', 'ENG_MET'),
  ('ENG_MET_02', 'Mensuração do Trabalho', 'ENG_MET'),
  ('ENG_PRO_01', 'Arquitetura e Projeto do Produto', 'ENG_PRO'),
  ('ENG_PRO_02', 'Integração do Desenvolvimento', 'ENG_PRO'),
  ('ENG_PRO_03', 'Processo de Desenvolvimento de Produtos', 'ENG_PRO'),
  ('ENG_PRO_04', 'Validação e Engenharia Reversa', 'ENG_PRO'),
  ('ENG_TRAB_01', 'Higiene, Segurança e Riscos Ocupacionais', 'ENG_TRAB'),
  ('ENG_TRAB_02', 'Projeto do Trabalho', 'ENG_TRAB'),
  ('ERG_01', 'Análise e Projeto Ergonômico', 'ERG'),
  ('ERG_02', 'Fundamentos de Ergonomia', 'ERG'),
  ('GES_INO_01', 'Fundamentos, Estratégia e Métodos de Inovação', 'GES_INO'),
  ('GES_INO_02', 'Gestão da Tecnologia', 'GES_INO'),
  ('GES_CUS_01', 'Análise Custo-Volume-Lucro e Custos para Decisão', 'GES_CUS'),
  ('GES_CUS_02', 'Contabilidade de Custos', 'GES_CUS'),
  ('GES_OPE_01', 'Estratégia de Operações', 'GES_OPE'),
  ('GES_OPE_02', 'Localização e Arranjo Físico', 'GES_OPE'),
  ('GES_OPE_03', 'Manufatura e Automação', 'GES_OPE'),
  ('GES_OPE_04', 'Medição de Desempenho de Operações', 'GES_OPE'),
  ('GES_OPE_05', 'Processos e Sistemas Produtivos', 'GES_OPE'),
  ('GES_OPE_06', 'Produção Enxuta e Just in Time', 'GES_OPE'),
  ('GES_PES_01', 'Comportamento e Desenvolvimento de Pessoas', 'GES_PES'),
  ('GES_PES_02', 'Planejamento e Provimento de Pessoas', 'GES_PES'),
  ('GES_PROJ_01', 'Áreas de Gerenciamento', 'GES_PROJ'),
  ('GES_PROJ_02', 'Cronograma e Redes', 'GES_PROJ'),
  ('GES_PROJ_03', 'Fundamentos de Projetos', 'GES_PROJ'),
  ('GES_PROJ_04', 'Governança de Projetos', 'GES_PROJ'),
  ('GES_PROJ_05', 'Integração, Iniciação e Controle', 'GES_PROJ'),
  ('GES_PROJ_06', 'Métodos Ágeis e Visuais', 'GES_PROJ'),
  ('GES_EST_01', 'Análise Estratégica', 'GES_EST'),
  ('GES_EST_02', 'Formulação Estratégica', 'GES_EST'),
  ('GES_EST_03', 'Implementação Estratégica', 'GES_EST'),
  ('GES_EST_04', 'Marketing', 'GES_EST'),
  ('GES_FIN_01', 'Finanças Corporativas', 'GES_FIN'),
  ('GES_FIN_02', 'Mercados, Risco e Retorno', 'GES_FIN'),
  ('GES_ORG_01', 'Decisão e Conhecimento Organizacional', 'GES_ORG'),
  ('GES_ORG_02', 'Gestão por Processos', 'GES_ORG'),
  ('GES_ORG_03', 'Organização, Governança e Desempenho', 'GES_ORG'),
  ('LOG_CAD_01', 'Armazenagem e Movimentação', 'LOG_CAD'),
  ('LOG_CAD_02', 'Distribuição e Transportes', 'LOG_CAD'),
  ('LOG_CAD_03', 'Fundamentos, Nível de Serviço e Operadores', 'LOG_CAD'),
  ('LOG_CAD_04', 'Gestão da Cadeia de Suprimentos', 'LOG_CAD'),
  ('LOG_CAD_05', 'Gestão de Estoques', 'LOG_CAD'),
  ('LOG_CAD_06', 'Tecnologias Logísticas', 'LOG_CAD'),
  ('MAN_CONF_01', 'Confiabilidade: Fundamentos, Sistemas e Indicadores', 'MAN_CONF'),
  ('MAN_CONF_02', 'Estratégias de Manutenção', 'MAN_CONF'),
  ('MAN_CONF_03', 'Gestão da Manutenção', 'MAN_CONF'),
  ('PES_OP_01', 'Apoio à Decisão', 'PES_OP'),
  ('PES_OP_02', 'Fundamentos, Simulação e Processos Estocásticos', 'PES_OP'),
  ('PES_OP_03', 'Otimização Discreta e em Redes', 'PES_OP'),
  ('PES_OP_04', 'Programação Linear e Não Linear', 'PES_OP'),
  ('PCP_01', 'Planejamento Agregado e da Capacidade', 'PCP'),
  ('PCP_02', 'Plano Mestre e Necessidades de Materiais', 'PCP'),
  ('PCP_03', 'Previsão de Demanda', 'PCP'),
  ('PCP_04', 'Programação, Balanceamento e Restrições', 'PCP'),
  ('PCP_05', 'Sistemas de PCP', 'PCP'),
  ('QUA_01', 'Ferramentas da Qualidade', 'QUA'),
  ('QUA_02', 'Fundamentos da Qualidade', 'QUA'),
  ('QUA_03', 'Gestão da Qualidade Total', 'QUA'),
  ('QUA_04', 'Melhoria e Padronização', 'QUA'),
  ('QUA_05', 'Planejamento e Controle da Qualidade', 'QUA'),
  ('SIS_INF_01', 'Gestão e Infraestrutura da Informação', 'SIS_INF'),
  ('SIS_INF_02', 'Sistemas Gerenciais e Integrados', 'SIS_INF'),
  ('SUS_01', 'Gestão Ambiental', 'SUS'),
  ('SUS_02', 'Produção Sustentável', 'SUS'),
  ('SUS_03', 'Resíduos e Poluição', 'SUS')
ON CONFLICT (codigo) DO UPDATE SET nome = EXCLUDED.nome, disciplina_codigo = EXCLUDED.disciplina_codigo;

-- Subassuntos (227)
INSERT INTO subassuntos (codigo, nome, assunto_codigo) VALUES
  ('ECO_01_001', 'Ciclos, Produto e Renda', 'ECO_01'),
  ('ECO_01_002', 'Comércio Internacional e Vantagens Comparativas', 'ECO_01'),
  ('ECO_01_003', 'Inflação', 'ECO_01'),
  ('ECO_01_004', 'Moeda e Preferência pela Liquidez', 'ECO_01'),
  ('ECO_01_005', 'Políticas Fiscal e Monetária', 'ECO_01'),
  ('ECO_02_001', 'Estruturas de Mercado e Regulação', 'ECO_02'),
  ('ECO_02_002', 'Oferta, Demanda e Elasticidade', 'ECO_02'),
  ('ECO_02_003', 'Teoria da Firma: Produção, Custos e Escala', 'ECO_02'),
  ('ENG_MET_01_001', 'Economia de Movimentos, Therbligs e Diagrama Bimanual', 'ENG_MET_01'),
  ('ENG_MET_01_002', 'Fluxogramas e Mapeamento de Processos (ASME)', 'ENG_MET_01'),
  ('ENG_MET_01_003', 'Melhoria do Método de Trabalho', 'ENG_MET_01'),
  ('ENG_MET_01_004', 'Padronização e Estabilização', 'ENG_MET_01'),
  ('ENG_MET_02_001', 'Amostragem do Trabalho', 'ENG_MET_02'),
  ('ENG_MET_02_002', 'Cronometragem e Tempos-Padrão', 'ENG_MET_02'),
  ('ENG_MET_02_003', 'Curva de Aprendizagem', 'ENG_MET_02'),
  ('ENG_MET_02_004', 'Tempos Predeterminados (MTM)', 'ENG_MET_02'),
  ('ENG_PRO_01_001', 'Arquitetura e Modularidade', 'ENG_PRO_01'),
  ('ENG_PRO_01_002', 'Design for X (DFX): Ecodesign e Desmontagem', 'ENG_PRO_01'),
  ('ENG_PRO_01_003', 'Projeto de Embalagens', 'ENG_PRO_01'),
  ('ENG_PRO_02_001', 'CAD/CAM/CAE no Desenvolvimento', 'ENG_PRO_02'),
  ('ENG_PRO_02_002', 'Engenharia Simultânea e Equipes', 'ENG_PRO_02'),
  ('ENG_PRO_03_001', 'Casa da Qualidade e Requisitos (QFD)', 'ENG_PRO_03'),
  ('ENG_PRO_03_002', 'Ciclo de Vida do Produto', 'ENG_PRO_03'),
  ('ENG_PRO_03_003', 'Metodologia de Projeto e Matriz Morfológica', 'ENG_PRO_03'),
  ('ENG_PRO_03_004', 'Modelos e Fases do PDP', 'ENG_PRO_03'),
  ('ENG_PRO_03_005', 'Planejamento e Viabilidade', 'ENG_PRO_03'),
  ('ENG_PRO_03_006', 'Projeto Conceitual e Seleção de Conceitos', 'ENG_PRO_03'),
  ('ENG_PRO_03_007', 'Projeto Informacional', 'ENG_PRO_03'),
  ('ENG_PRO_03_008', 'Projeto Preliminar e Detalhado', 'ENG_PRO_03'),
  ('ENG_PRO_04_001', 'Engenharia Reversa', 'ENG_PRO_04'),
  ('ENG_PRO_04_002', 'Prototipagem e Testes', 'ENG_PRO_04'),
  ('ENG_TRAB_01_001', 'Acidentes do Trabalho e Prevenção', 'ENG_TRAB_01'),
  ('ENG_TRAB_01_002', 'Agentes Físicos Ocupacionais', 'ENG_TRAB_01'),
  ('ENG_TRAB_01_003', 'Análise e Mapeamento de Riscos', 'ENG_TRAB_01'),
  ('ENG_TRAB_01_004', 'EPI e Proteção Respiratória', 'ENG_TRAB_01'),
  ('ENG_TRAB_01_005', 'Sistemas de Gestão de SST', 'ENG_TRAB_01'),
  ('ENG_TRAB_02_001', 'Condições e Jornada de Trabalho', 'ENG_TRAB_02'),
  ('ENG_TRAB_02_002', 'Desenho de Cargos e Enriquecimento do Trabalho', 'ENG_TRAB_02'),
  ('ENG_TRAB_02_003', 'Organização e Controle do Trabalho', 'ENG_TRAB_02'),
  ('ERG_01_001', 'AET e Integração com Métodos', 'ERG_01'),
  ('ERG_01_002', 'Antropometria, Postura e Postos de Trabalho', 'ERG_01'),
  ('ERG_01_003', 'Conforto Ambiental e Ergonomia Visual', 'ERG_01'),
  ('ERG_02_001', 'Conceitos, Domínios e Classificação da Ergonomia', 'ERG_02'),
  ('GES_INO_01_001', 'Ambidestria, Risco e Incerteza', 'GES_INO_01'),
  ('GES_INO_01_002', 'Ambiente e Sistemas de Inovação', 'GES_INO_01'),
  ('GES_INO_01_003', 'Design Thinking e Métodos de Ideação', 'GES_INO_01'),
  ('GES_INO_01_004', 'Modelos e Processo de Inovação', 'GES_INO_01'),
  ('GES_INO_01_005', 'Tipos e Graus de Inovação', 'GES_INO_01'),
  ('GES_INO_02_001', 'Aquisição de Tecnologia', 'GES_INO_02'),
  ('GES_INO_02_002', 'Organização de P&D', 'GES_INO_02'),
  ('GES_CUS_01_001', 'Custos de Oportunidade e Custos Afundados', 'GES_CUS_01'),
  ('GES_CUS_01_002', 'Formação de Preços', 'GES_CUS_01'),
  ('GES_CUS_01_003', 'Margens e Ponto de Equilíbrio', 'GES_CUS_01'),
  ('GES_CUS_02_001', 'Classificação de Custos', 'GES_CUS_02'),
  ('GES_CUS_02_002', 'CMV e Resultado Operacional', 'GES_CUS_02'),
  ('GES_CUS_02_003', 'Custos Unitários e Apropriação', 'GES_CUS_02'),
  ('GES_CUS_02_004', 'Estimativa de Custos e Fator de Escala', 'GES_CUS_02'),
  ('GES_CUS_02_005', 'Métodos de Custeio', 'GES_CUS_02'),
  ('GES_OPE_01_001', 'Estrutura e Infraestrutura', 'GES_OPE_01'),
  ('GES_OPE_01_002', 'Formulação e Alinhamento', 'GES_OPE_01'),
  ('GES_OPE_01_003', 'Prioridades Competitivas e Matriz de Desempenho', 'GES_OPE_01'),
  ('GES_OPE_02_001', 'Critérios de Localização', 'GES_OPE_02'),
  ('GES_OPE_02_002', 'Modelos de Localização', 'GES_OPE_02'),
  ('GES_OPE_02_003', 'Tipos de Arranjo Físico', 'GES_OPE_02'),
  ('GES_OPE_03_001', 'Indústria 4.0 e IoT Industrial', 'GES_OPE_03'),
  ('GES_OPE_03_002', 'Integração CAD/CAM e CNC', 'GES_OPE_03'),
  ('GES_OPE_03_003', 'Manufatura Integrada (CIM)', 'GES_OPE_03'),
  ('GES_OPE_03_004', 'Sistemas Flexíveis e Células', 'GES_OPE_03'),
  ('GES_OPE_04_001', 'Capacidade, Utilização e Eficiência', 'GES_OPE_04'),
  ('GES_OPE_04_002', 'Lei de Little, Fluxo e Lead Time', 'GES_OPE_04'),
  ('GES_OPE_04_003', 'Produtividade e Indicadores Operacionais', 'GES_OPE_04'),
  ('GES_OPE_05_001', 'Estratégias de Atendimento à Demanda (MTS/MTO/ATO)', 'GES_OPE_05'),
  ('GES_OPE_05_002', 'Paradigmas de Manufatura', 'GES_OPE_05'),
  ('GES_OPE_05_003', 'Projeto de Serviços', 'GES_OPE_05'),
  ('GES_OPE_05_004', 'Tipologia e Fluxos de Processos', 'GES_OPE_05'),
  ('GES_OPE_06_001', 'Princípios e Desperdícios Lean/JIT', 'GES_OPE_06'),
  ('GES_OPE_06_002', 'Produção Puxada e Kanban', 'GES_OPE_06'),
  ('GES_OPE_06_003', 'Trabalho Padronizado, SMED e Poka-Yoke', 'GES_OPE_06'),
  ('GES_PES_01_001', 'Avaliação de Desempenho e Remuneração', 'GES_PES_01'),
  ('GES_PES_01_002', 'Equipes e Trabalho Autodirigido', 'GES_PES_01'),
  ('GES_PES_01_003', 'Motivação e Liderança', 'GES_PES_01'),
  ('GES_PES_01_004', 'Treinamento e Desenvolvimento', 'GES_PES_01'),
  ('GES_PES_02_001', 'Planejamento da Força de Trabalho e Indicadores', 'GES_PES_02'),
  ('GES_PES_02_002', 'Recrutamento e Seleção', 'GES_PES_02'),
  ('GES_PROJ_01_001', 'Aquisições e Contratos', 'GES_PROJ_01'),
  ('GES_PROJ_01_002', 'Comunicação e Partes Interessadas', 'GES_PROJ_01'),
  ('GES_PROJ_01_003', 'Custos do Projeto', 'GES_PROJ_01'),
  ('GES_PROJ_01_004', 'Escopo do Projeto', 'GES_PROJ_01'),
  ('GES_PROJ_01_005', 'Qualidade do Projeto', 'GES_PROJ_01'),
  ('GES_PROJ_01_006', 'Recursos do Projeto', 'GES_PROJ_01'),
  ('GES_PROJ_01_007', 'Riscos do Projeto', 'GES_PROJ_01'),
  ('GES_PROJ_02_001', 'Compressão de Cronograma', 'GES_PROJ_02'),
  ('GES_PROJ_02_002', 'PERT Probabilístico', 'GES_PROJ_02'),
  ('GES_PROJ_02_003', 'Redes, Caminho Crítico e Folgas', 'GES_PROJ_02'),
  ('GES_PROJ_03_001', 'Conceitos e Ciclo de Vida', 'GES_PROJ_03'),
  ('GES_PROJ_03_002', 'Grupos de Processos e Referenciais', 'GES_PROJ_03'),
  ('GES_PROJ_03_003', 'Tripla Restrição', 'GES_PROJ_03'),
  ('GES_PROJ_04_001', 'Estruturas e Maturidade', 'GES_PROJ_04'),
  ('GES_PROJ_04_002', 'Portfólio e Priorização', 'GES_PROJ_04'),
  ('GES_PROJ_05_001', 'Indicadores e Valor Agregado', 'GES_PROJ_05'),
  ('GES_PROJ_05_002', 'Planejamento e Controle Integrados', 'GES_PROJ_05'),
  ('GES_PROJ_05_003', 'Termo de Abertura', 'GES_PROJ_05'),
  ('GES_PROJ_06_001', 'Métodos Ágeis, Scrum e Quadro Kanban', 'GES_PROJ_06'),
  ('GES_PROJ_06_002', 'Project Model Canvas', 'GES_PROJ_06'),
  ('GES_EST_01_001', 'Análise Setorial, Cinco Forças e Cadeia de Valor', 'GES_EST_01'),
  ('GES_EST_01_002', 'Crescimento e Portfólio', 'GES_EST_01'),
  ('GES_EST_01_003', 'Estratégias Genéricas e Vantagem Competitiva', 'GES_EST_01'),
  ('GES_EST_01_004', 'Recursos, Competências e VBR', 'GES_EST_01'),
  ('GES_EST_02_001', 'Diagnóstico Estratégico', 'GES_EST_02'),
  ('GES_EST_02_002', 'Escolas e Níveis de Estratégia', 'GES_EST_02'),
  ('GES_EST_02_003', 'Missão, Visão e Identidade', 'GES_EST_02'),
  ('GES_EST_03_001', 'BSC, Mapas Estratégicos e Medição de Desempenho', 'GES_EST_03'),
  ('GES_EST_03_002', 'Desdobramento de Diretrizes (Hoshin Kanri)', 'GES_EST_03'),
  ('GES_EST_04_001', 'Comportamento e Segmentação', 'GES_EST_04'),
  ('GES_EST_04_002', 'Composto de Marketing (4 Ps)', 'GES_EST_04'),
  ('GES_EST_04_003', 'Planejamento e Estratégias de Marketing', 'GES_EST_04'),
  ('GES_FIN_01_001', 'Alavancagem', 'GES_FIN_01'),
  ('GES_FIN_01_002', 'Custo de Capital e Criação de Valor', 'GES_FIN_01'),
  ('GES_FIN_01_003', 'Demonstrações e Indicadores', 'GES_FIN_01'),
  ('GES_FIN_02_001', 'CAPM e Risco Sistemático', 'GES_FIN_02'),
  ('GES_FIN_02_002', 'Desempenho Ajustado ao Risco', 'GES_FIN_02'),
  ('GES_FIN_02_003', 'Hedge e Correlação', 'GES_FIN_02'),
  ('GES_FIN_02_004', 'Mercados e Curva de Juros', 'GES_FIN_02'),
  ('GES_FIN_02_005', 'Simulação de Risco', 'GES_FIN_02'),
  ('GES_ORG_01_001', 'Gestão do Conhecimento e Inteligência Competitiva', 'GES_ORG_01'),
  ('GES_ORG_01_002', 'Processo Decisório e Decisão em Grupo', 'GES_ORG_01'),
  ('GES_ORG_01_003', 'Racionalidade e Vieses', 'GES_ORG_01'),
  ('GES_ORG_02_001', 'BPM e Automação', 'GES_ORG_02'),
  ('GES_ORG_02_002', 'Mapeamento, Interfaces e Handoffs', 'GES_ORG_02'),
  ('GES_ORG_02_003', 'Redesenho e Reengenharia', 'GES_ORG_02'),
  ('GES_ORG_03_001', 'Controle Organizacional e Níveis de Planejamento', 'GES_ORG_03'),
  ('GES_ORG_03_002', 'Empreendedorismo e Plano de Negócios', 'GES_ORG_03'),
  ('GES_ORG_03_003', 'Estruturas e Mintzberg', 'GES_ORG_03'),
  ('GES_ORG_03_004', 'Governança Corporativa, Ética e Compliance', 'GES_ORG_03'),
  ('GES_ORG_03_005', 'Mudança Organizacional', 'GES_ORG_03'),
  ('LOG_CAD_01_001', 'Decisões de Armazenagem', 'LOG_CAD_01'),
  ('LOG_CAD_01_002', 'Movimentação, Unitização e Embalagem', 'LOG_CAD_01'),
  ('LOG_CAD_02_001', 'Canais e Modais', 'LOG_CAD_02'),
  ('LOG_CAD_02_002', 'Fluxos Reversos', 'LOG_CAD_02'),
  ('LOG_CAD_02_003', 'Redes e Configurações Logísticas', 'LOG_CAD_02'),
  ('LOG_CAD_03_001', 'Atividades e Estratégia Logística', 'LOG_CAD_03'),
  ('LOG_CAD_03_002', 'Disponibilidade e Trade-offs', 'LOG_CAD_03'),
  ('LOG_CAD_03_003', 'Operadores Logísticos e 4PL', 'LOG_CAD_03'),
  ('LOG_CAD_04_001', 'Compras, Fornecedores e Negociação', 'LOG_CAD_04'),
  ('LOG_CAD_04_002', 'Integração da Cadeia de Suprimentos', 'LOG_CAD_04'),
  ('LOG_CAD_04_003', 'Reposição Colaborativa (CR/VMI)', 'LOG_CAD_04'),
  ('LOG_CAD_05_001', 'Classificação ABC e Tipos de Estoque', 'LOG_CAD_05'),
  ('LOG_CAD_05_002', 'Custos e Indicadores de Estoque', 'LOG_CAD_05'),
  ('LOG_CAD_05_003', 'Lote Econômico de Compra', 'LOG_CAD_05'),
  ('LOG_CAD_05_004', 'Reposição e Ponto de Pedido', 'LOG_CAD_05'),
  ('LOG_CAD_06_001', 'EDI e Integração de Dados', 'LOG_CAD_06'),
  ('LOG_CAD_06_002', 'Identificação e Rastreabilidade', 'LOG_CAD_06'),
  ('MAN_CONF_01_001', 'Confiabilidade e Taxa de Falhas', 'MAN_CONF_01'),
  ('MAN_CONF_01_002', 'Disponibilidade, MTBF e MTTR', 'MAN_CONF_01'),
  ('MAN_CONF_01_003', 'Série, Paralelo e Standby', 'MAN_CONF_01'),
  ('MAN_CONF_02_001', 'Tipos e Monitoramento de Condição', 'MAN_CONF_02'),
  ('MAN_CONF_02_002', 'TPM e Manutenção Autônoma', 'MAN_CONF_02'),
  ('MAN_CONF_03_001', 'Organização e Manutenibilidade', 'MAN_CONF_03'),
  ('MAN_CONF_03_002', 'Planejamento e Controle', 'MAN_CONF_03'),
  ('PES_OP_01_001', 'Análise Envoltória de Dados (DEA)', 'PES_OP_01'),
  ('PES_OP_01_002', 'Apoio Multicritério à Decisão (AHP)', 'PES_OP_01'),
  ('PES_OP_01_003', 'Decisão sob Incerteza', 'PES_OP_01'),
  ('PES_OP_01_004', 'Risco, Valor Esperado e Utilidade', 'PES_OP_01'),
  ('PES_OP_01_005', 'Teoria dos Jogos e Equilíbrio', 'PES_OP_01'),
  ('PES_OP_02_001', 'Cadeias de Markov', 'PES_OP_02'),
  ('PES_OP_02_002', 'Eventos Discretos e Monte Carlo', 'PES_OP_02'),
  ('PES_OP_02_003', 'Metodologia e Fases da PO', 'PES_OP_02'),
  ('PES_OP_02_004', 'Modelos e Desempenho de Filas', 'PES_OP_02'),
  ('PES_OP_03_001', 'Otimização Combinatória e Heurísticas', 'PES_OP_03'),
  ('PES_OP_03_002', 'Redes, Transporte e Roteirização', 'PES_OP_03'),
  ('PES_OP_04_001', 'Formulação e Modelagem', 'PES_OP_04'),
  ('PES_OP_04_002', 'Método Simplex', 'PES_OP_04'),
  ('PES_OP_04_003', 'Programação Não Linear', 'PES_OP_04'),
  ('PES_OP_04_004', 'Sensibilidade e Dualidade', 'PES_OP_04'),
  ('PES_OP_04_005', 'Solução Gráfica', 'PES_OP_04'),
  ('PCP_01_001', 'Estratégias de Capacidade', 'PCP_01'),
  ('PCP_01_002', 'Estratégias de Planejamento Agregado', 'PCP_01'),
  ('PCP_01_003', 'Planejamento da Capacidade e CRP', 'PCP_01'),
  ('PCP_02_001', 'Estrutura do Produto (BOM) e Cálculo de Necessidades', 'PCP_02'),
  ('PCP_02_002', 'MPS: Estrutura e Viabilidade', 'PCP_02'),
  ('PCP_02_003', 'MRP e MRP II', 'PCP_02'),
  ('PCP_03_001', 'Gestão da Demanda', 'PCP_03'),
  ('PCP_03_002', 'Métodos de Séries Temporais', 'PCP_03'),
  ('PCP_03_003', 'Métodos Qualitativos', 'PCP_03'),
  ('PCP_03_004', 'Modelos Causais', 'PCP_03'),
  ('PCP_04_001', 'Balanceamento de Linha: Tempo de Ciclo e Postos', 'PCP_04'),
  ('PCP_04_002', 'Carregamento e Sequenciamento', 'PCP_04'),
  ('PCP_04_003', 'Gargalos e Tambor-Pulmão-Corda (TOC)', 'PCP_04'),
  ('PCP_05_001', 'Controle e Acompanhamento da Produção', 'PCP_05'),
  ('PCP_05_002', 'Níveis de Planejamento', 'PCP_05'),
  ('PCP_05_003', 'Sistemas APS e Integração MRP/ERP no PCP', 'PCP_05'),
  ('QUA_01_001', 'Análise de Falhas e Causa Raiz (FMEA, FTA, 5 Porquês)', 'QUA_01'),
  ('QUA_01_002', 'Ferramentas Básicas', 'QUA_01'),
  ('QUA_01_003', 'Ferramentas Gerenciais', 'QUA_01'),
  ('QUA_02_001', 'Conceitos e Dimensões da Qualidade', 'QUA_02'),
  ('QUA_02_002', 'Gurus e Filosofias', 'QUA_02'),
  ('QUA_02_003', 'Qualidade em Serviços', 'QUA_02'),
  ('QUA_03_001', 'Cliente, Pessoas e Organização', 'QUA_03'),
  ('QUA_03_002', 'Modelos de Excelência (MEG)', 'QUA_03'),
  ('QUA_03_003', 'Princípios da GQT', 'QUA_03'),
  ('QUA_04_001', '5S', 'QUA_04'),
  ('QUA_04_002', 'Benchmarking', 'QUA_04'),
  ('QUA_04_003', 'Padronização e Procedimentos', 'QUA_04'),
  ('QUA_04_004', 'PDCA e Melhoria Contínua', 'QUA_04'),
  ('QUA_04_005', 'Seis Sigma e DMAIC', 'QUA_04'),
  ('QUA_05_001', 'Controle Estatístico de Processo (CEP) e Capacidade', 'QUA_05'),
  ('QUA_05_002', 'Custos da Qualidade', 'QUA_05'),
  ('QUA_05_003', 'Inspeção, Amostragem de Aceitação e Não Conformidades', 'QUA_05'),
  ('QUA_05_004', 'Planejamento da Qualidade', 'QUA_05'),
  ('QUA_05_005', 'Qualidade de Fornecedores', 'QUA_05'),
  ('QUA_05_006', 'Sistemas de Gestão da Qualidade e ISO 9000', 'QUA_05'),
  ('SIS_INF_01_001', 'Computação em Nuvem e SaaS', 'SIS_INF_01'),
  ('SIS_INF_01_002', 'Estratégia, TI e Recursos Informacionais', 'SIS_INF_01'),
  ('SIS_INF_02_001', 'ERP: Módulos, Arquitetura e Implantação', 'SIS_INF_02'),
  ('SIS_INF_02_002', 'Sistemas de Apoio à Decisão (SAD)', 'SIS_INF_02'),
  ('SIS_INF_02_003', 'Sistemas de Informação Gerencial (SIG) e Níveis Decisórios', 'SIS_INF_02'),
  ('SUS_01_001', 'Desenvolvimento Sustentável, TBL e Responsabilidade Social', 'SUS_01'),
  ('SUS_01_002', 'Gestão Ambiental Empresarial e Práticas Sustentáveis', 'SUS_01'),
  ('SUS_01_003', 'Gestão de Carbono e REDD', 'SUS_01'),
  ('SUS_01_004', 'Licenciamento e Avaliação de Impacto Ambiental', 'SUS_01'),
  ('SUS_01_005', 'Sistemas de Gestão Ambiental (ISO 14001)', 'SUS_01'),
  ('SUS_02_001', 'Avaliação do Ciclo de Vida', 'SUS_02'),
  ('SUS_02_002', 'Matriz e Eficiência Energética', 'SUS_02'),
  ('SUS_02_003', 'Produção Limpa e Ecoeficiência', 'SUS_02'),
  ('SUS_03_001', 'Controle da Poluição Industrial', 'SUS_03'),
  ('SUS_03_002', 'Gestão de Resíduos Sólidos e Rejeitos', 'SUS_03'),
  ('SUS_03_003', 'Tratamento e Reuso de Efluentes', 'SUS_03')
ON CONFLICT (codigo) DO UPDATE SET nome = EXCLUDED.nome, assunto_codigo = EXCLUDED.assunto_codigo;

COMMIT;
