-- Núcleo Básico de Engenharia — ETAPA2 — carga no schema taxonomia
-- Gerado a partir de arvores/NUCLEO_BASICO_CORRIGIDO_ETAPA2.md
-- 15 disciplinas, 98 assuntos, 361 subassuntos
--
-- AJUSTE OBRIGATÓRIO: substitua 'NUCLEO_BASICO' abaixo pelo familia_id existente em taxonomia._familias.
-- O script é idempotente (upsert por chave primária) e roda em uma única transação.

begin;

insert into taxonomia.disciplinas (disciplina_id, familia_id, name, ordem, ativo)
select d.disciplina_id, 'NUCLEO_BASICO', d.name, d.ordem, true
from (values
  ('ALG_LIN', 'Álgebra Linear', 1),
  ('CAL_DIF', 'Cálculo Diferencial e Integral', 2),
  ('CIE_MAT', 'Ciência dos Materiais', 3),
  ('DES_TEC', 'Desenho Técnico', 4),
  ('ENG_ECO', 'Engenharia Econômica', 5),
  ('FIS_GER', 'Física Geral', 6),
  ('MAT_BAS', 'Matemática Básica', 7),
  ('MEC_FLU', 'Mecânica dos Fluidos', 8),
  ('MEC_GER', 'Mecânica Geral', 9),
  ('METROL', 'Metrologia', 10),
  ('PRB_EST', 'Probabilidade e Estatística', 11),
  ('QUI_GER', 'Química Geral', 12),
  ('RES_MAT', 'Resistência dos Materiais', 13),
  ('TERMOD', 'Termodinâmica', 14),
  ('TRA_CAL', 'Transferência de Calor', 15)
) as d(disciplina_id, name, ordem)
on conflict (disciplina_id) do update
  set familia_id = excluded.familia_id, name = excluded.name, ordem = excluded.ordem, ativo = true;

insert into taxonomia.assuntos (assunto_id, disciplina_id, name, ordem, ativo)
values
  ('ALG_LIN_01', 'ALG_LIN', 'Espaços Vetoriais', 1, true),
  ('ALG_LIN_02', 'ALG_LIN', 'Matrizes e Determinantes', 2, true),
  ('ALG_LIN_03', 'ALG_LIN', 'Sistemas Lineares', 3, true),
  ('ALG_LIN_04', 'ALG_LIN', 'Transformações Lineares', 4, true),
  ('CAL_DIF_01', 'CAL_DIF', 'Cálculo Multivariável e Vetorial', 1, true),
  ('CAL_DIF_02', 'CAL_DIF', 'Derivadas', 2, true),
  ('CAL_DIF_03', 'CAL_DIF', 'Equações Diferenciais Ordinárias', 3, true),
  ('CAL_DIF_04', 'CAL_DIF', 'Integrais', 4, true),
  ('CAL_DIF_05', 'CAL_DIF', 'Limites e Continuidade', 5, true),
  ('CAL_DIF_06', 'CAL_DIF', 'Métodos Numéricos', 6, true),
  ('CIE_MAT_01', 'CIE_MAT', 'Classificação e Seleção', 1, true),
  ('CIE_MAT_02', 'CIE_MAT', 'Corrosão e Degradação', 2, true),
  ('CIE_MAT_03', 'CIE_MAT', 'Diagramas de Fases', 3, true),
  ('CIE_MAT_04', 'CIE_MAT', 'Ensaios de Materiais', 4, true),
  ('CIE_MAT_05', 'CIE_MAT', 'Estrutura Atômica e Cristalina', 5, true),
  ('CIE_MAT_06', 'CIE_MAT', 'Falha e Fratura', 6, true),
  ('CIE_MAT_07', 'CIE_MAT', 'Materiais Cerâmicos e Poliméricos', 7, true),
  ('CIE_MAT_08', 'CIE_MAT', 'Materiais Metálicos e Ligas', 8, true),
  ('CIE_MAT_09', 'CIE_MAT', 'Mecanismos de Endurecimento', 9, true),
  ('CIE_MAT_10', 'CIE_MAT', 'Propriedades Físicas', 10, true),
  ('CIE_MAT_11', 'CIE_MAT', 'Propriedades Mecânicas', 11, true),
  ('CIE_MAT_12', 'CIE_MAT', 'Tratamentos Térmicos', 12, true),
  ('DES_TEC_01', 'DES_TEC', 'CAD e Computação Gráfica', 1, true),
  ('DES_TEC_02', 'DES_TEC', 'Normas, Cotagem e Tolerâncias', 2, true),
  ('DES_TEC_03', 'DES_TEC', 'Projeções, Vistas e Perspectivas', 3, true),
  ('ENG_ECO_01', 'ENG_ECO', 'Análise de Investimentos', 1, true),
  ('ENG_ECO_02', 'ENG_ECO', 'Matemática Financeira', 2, true),
  ('FIS_GER_01', 'FIS_GER', 'Eletrodinâmica', 1, true),
  ('FIS_GER_02', 'FIS_GER', 'Eletrostática', 2, true),
  ('FIS_GER_03', 'FIS_GER', 'Física Moderna', 3, true),
  ('FIS_GER_04', 'FIS_GER', 'Magnetismo e Indução Eletromagnética', 4, true),
  ('FIS_GER_05', 'FIS_GER', 'Ondas, Acústica e Óptica', 5, true),
  ('MAT_BAS_01', 'MAT_BAS', 'Álgebra Elementar', 1, true),
  ('MAT_BAS_02', 'MAT_BAS', 'Análise Combinatória', 2, true),
  ('MAT_BAS_03', 'MAT_BAS', 'Aritmética e Proporcionalidade', 3, true),
  ('MAT_BAS_04', 'MAT_BAS', 'Funções', 4, true),
  ('MAT_BAS_05', 'MAT_BAS', 'Geometria Analítica', 5, true),
  ('MAT_BAS_06', 'MAT_BAS', 'Geometria Espacial', 6, true),
  ('MAT_BAS_07', 'MAT_BAS', 'Geometria Plana', 7, true),
  ('MAT_BAS_08', 'MAT_BAS', 'Sequências e Progressões', 8, true),
  ('MAT_BAS_09', 'MAT_BAS', 'Teoria dos Conjuntos', 9, true),
  ('MAT_BAS_10', 'MAT_BAS', 'Trigonometria', 10, true),
  ('MEC_FLU_01', 'MEC_FLU', 'Análise Dimensional e Semelhança', 1, true),
  ('MEC_FLU_02', 'MEC_FLU', 'Cinemática dos Fluidos', 2, true),
  ('MEC_FLU_03', 'MEC_FLU', 'Dinâmica dos Fluidos', 3, true),
  ('MEC_FLU_04', 'MEC_FLU', 'Escoamento Externo', 4, true),
  ('MEC_FLU_05', 'MEC_FLU', 'Escoamento Interno em Condutos', 5, true),
  ('MEC_FLU_06', 'MEC_FLU', 'Estática dos Fluidos', 6, true),
  ('MEC_FLU_07', 'MEC_FLU', 'Medição de Escoamentos', 7, true),
  ('MEC_FLU_08', 'MEC_FLU', 'Propriedades dos Fluidos', 8, true),
  ('MEC_GER_01', 'MEC_GER', 'Cinemática da Partícula', 1, true),
  ('MEC_GER_02', 'MEC_GER', 'Cinemática do Corpo Rígido', 2, true),
  ('MEC_GER_03', 'MEC_GER', 'Dinâmica da Partícula', 3, true),
  ('MEC_GER_04', 'MEC_GER', 'Dinâmica do Corpo Rígido', 4, true),
  ('MEC_GER_05', 'MEC_GER', 'Estática', 5, true),
  ('METROL_01', 'METROL', 'Calibração e Rastreabilidade', 1, true),
  ('METROL_02', 'METROL', 'Erros e Incertezas de Medição', 2, true),
  ('METROL_03', 'METROL', 'Fundamentos de Metrologia', 3, true),
  ('METROL_04', 'METROL', 'Instrumentos de Medição', 4, true),
  ('METROL_05', 'METROL', 'Sistema Internacional de Unidades', 5, true),
  ('METROL_06', 'METROL', 'Tolerâncias e Ajustes', 6, true),
  ('PRB_EST_01', 'PRB_EST', 'Correlação e Regressão', 1, true),
  ('PRB_EST_02', 'PRB_EST', 'Estatística Descritiva', 2, true),
  ('PRB_EST_03', 'PRB_EST', 'Inferência Estatística', 3, true),
  ('PRB_EST_04', 'PRB_EST', 'Probabilidade', 4, true),
  ('PRB_EST_05', 'PRB_EST', 'Variáveis Aleatórias e Distribuições', 5, true),
  ('QUI_GER_01', 'QUI_GER', 'Cinética Química', 1, true),
  ('QUI_GER_02', 'QUI_GER', 'Eletroquímica', 2, true),
  ('QUI_GER_03', 'QUI_GER', 'Equilíbrio Químico', 3, true),
  ('QUI_GER_04', 'QUI_GER', 'Estequiometria', 4, true),
  ('QUI_GER_05', 'QUI_GER', 'Estrutura Atômica e Periodicidade', 5, true),
  ('QUI_GER_06', 'QUI_GER', 'Funções Inorgânicas e Reações Químicas', 6, true),
  ('QUI_GER_07', 'QUI_GER', 'Soluções', 7, true),
  ('RES_MAT_01', 'RES_MAT', 'Critérios de Falha', 1, true),
  ('RES_MAT_02', 'RES_MAT', 'Esforços Solicitantes e Diagramas', 2, true),
  ('RES_MAT_03', 'RES_MAT', 'Flambagem e Estabilidade', 3, true),
  ('RES_MAT_04', 'RES_MAT', 'Flexão, Cisalhamento e Deflexão em Vigas', 4, true),
  ('RES_MAT_05', 'RES_MAT', 'Propriedades Geométricas de Seções Planas', 5, true),
  ('RES_MAT_06', 'RES_MAT', 'Tensão, Deformação e Carregamento Axial', 6, true),
  ('RES_MAT_07', 'RES_MAT', 'Tensões e Deformações Planas', 7, true),
  ('RES_MAT_08', 'RES_MAT', 'Torção', 8, true),
  ('TERMOD_01', 'TERMOD', 'Calorimetria', 1, true),
  ('TERMOD_02', 'TERMOD', 'Ciclos de Potência', 2, true),
  ('TERMOD_03', 'TERMOD', 'Equilíbrio de Fases', 3, true),
  ('TERMOD_04', 'TERMOD', 'Fundamentos da Termodinâmica', 4, true),
  ('TERMOD_05', 'TERMOD', 'Gases e Equações de Estado', 5, true),
  ('TERMOD_06', 'TERMOD', 'Primeira Lei da Termodinâmica', 6, true),
  ('TERMOD_07', 'TERMOD', 'Propriedades de Substâncias Puras', 7, true),
  ('TERMOD_08', 'TERMOD', 'Psicrometria', 8, true),
  ('TERMOD_09', 'TERMOD', 'Refrigeração e Bombas de Calor', 9, true),
  ('TERMOD_10', 'TERMOD', 'Relações Termodinâmicas', 10, true),
  ('TERMOD_11', 'TERMOD', 'Segunda Lei da Termodinâmica', 11, true),
  ('TERMOD_12', 'TERMOD', 'Termoquímica e Combustão', 12, true),
  ('TRA_CAL_01', 'TRA_CAL', 'Condução Térmica', 1, true),
  ('TRA_CAL_02', 'TRA_CAL', 'Convecção', 2, true),
  ('TRA_CAL_03', 'TRA_CAL', 'Fundamentos de Transferência de Calor', 3, true),
  ('TRA_CAL_04', 'TRA_CAL', 'Radiação Térmica', 4, true),
  ('TRA_CAL_05', 'TRA_CAL', 'Trocadores de Calor', 5, true)
on conflict (assunto_id) do update
  set disciplina_id = excluded.disciplina_id, name = excluded.name, ordem = excluded.ordem, ativo = true;

insert into taxonomia.subassuntos (subassunto_id, assunto_id, name, ordem, ativo)
values
  ('ALG_LIN_01_001', 'ALG_LIN_01', 'Espaços Vetoriais, Subespaços, Base e Dimensão', 1, true),
  ('ALG_LIN_01_002', 'ALG_LIN_01', 'Produto Interno e Ortogonalidade', 2, true),
  ('ALG_LIN_02_001', 'ALG_LIN_02', 'Determinantes', 1, true),
  ('ALG_LIN_02_002', 'ALG_LIN_02', 'Operações com Matrizes e Matriz Inversa', 2, true),
  ('ALG_LIN_03_001', 'ALG_LIN_03', 'Classificação, Posto e Sistemas Homogêneos', 1, true),
  ('ALG_LIN_03_002', 'ALG_LIN_03', 'Resolução de Sistemas Lineares', 2, true),
  ('ALG_LIN_04_001', 'ALG_LIN_04', 'Autovalores, Autovetores e Diagonalização', 1, true),
  ('ALG_LIN_04_002', 'ALG_LIN_04', 'Imagem e Núcleo', 2, true),
  ('ALG_LIN_04_003', 'ALG_LIN_04', 'Matriz de Transformação', 3, true),
  ('ALG_LIN_04_004', 'ALG_LIN_04', 'Propriedades de Transformações Lineares', 4, true),
  ('CAL_DIF_01_001', 'CAL_DIF_01', 'Campos Vetoriais e Campos Conservativos', 1, true),
  ('CAL_DIF_01_002', 'CAL_DIF_01', 'Extremos e Otimização', 2, true),
  ('CAL_DIF_01_003', 'CAL_DIF_01', 'Integrais Múltiplas', 3, true),
  ('CAL_DIF_02_001', 'CAL_DIF_02', 'Aplicações da Derivada', 1, true),
  ('CAL_DIF_02_002', 'CAL_DIF_02', 'Derivação Implícita', 2, true),
  ('CAL_DIF_02_003', 'CAL_DIF_02', 'Derivadas de Funções Elementares', 3, true),
  ('CAL_DIF_02_004', 'CAL_DIF_02', 'Regra da Cadeia', 4, true),
  ('CAL_DIF_03_001', 'CAL_DIF_03', 'EDOs de Primeira Ordem', 1, true),
  ('CAL_DIF_03_002', 'CAL_DIF_03', 'EDOs de Segunda Ordem', 2, true),
  ('CAL_DIF_03_003', 'CAL_DIF_03', 'Equações Diferenciais Lineares', 3, true),
  ('CAL_DIF_03_004', 'CAL_DIF_03', 'Transformada de Laplace', 4, true),
  ('CAL_DIF_04_001', 'CAL_DIF_04', 'Aplicações da Integral', 1, true),
  ('CAL_DIF_04_002', 'CAL_DIF_04', 'Integrais Definidas', 2, true),
  ('CAL_DIF_04_003', 'CAL_DIF_04', 'Integrais Indefinidas', 3, true),
  ('CAL_DIF_04_004', 'CAL_DIF_04', 'Métodos de Integração', 4, true),
  ('CAL_DIF_05_001', 'CAL_DIF_05', 'Cálculo de Limites e Continuidade de Funções', 1, true),
  ('CAL_DIF_05_002', 'CAL_DIF_05', 'Indeterminações', 2, true),
  ('CAL_DIF_06_001', 'CAL_DIF_06', 'Erros e Convergência Numérica', 1, true),
  ('CAL_DIF_06_002', 'CAL_DIF_06', 'Integração, Derivação e Sistemas Numéricos', 2, true),
  ('CAL_DIF_06_003', 'CAL_DIF_06', 'Solução Numérica de Equações Diferenciais', 3, true),
  ('CAL_DIF_06_004', 'CAL_DIF_06', 'Zeros de Funções (Newton-Raphson, Bisseção)', 4, true),
  ('CIE_MAT_01_001', 'CIE_MAT_01', 'Classificação dos Materiais', 1, true),
  ('CIE_MAT_01_002', 'CIE_MAT_01', 'Seleção de Materiais', 2, true),
  ('CIE_MAT_02_001', 'CIE_MAT_02', 'Corrosão Eletroquímica', 1, true),
  ('CIE_MAT_02_002', 'CIE_MAT_02', 'Corrosão Galvânica', 2, true),
  ('CIE_MAT_02_003', 'CIE_MAT_02', 'Proteção contra Corrosão', 3, true),
  ('CIE_MAT_03_001', 'CIE_MAT_03', 'Diagrama Ferro-Carbono', 1, true),
  ('CIE_MAT_03_002', 'CIE_MAT_03', 'Fases e Transformações', 2, true),
  ('CIE_MAT_04_001', 'CIE_MAT_04', 'Ensaio de Impacto', 1, true),
  ('CIE_MAT_04_002', 'CIE_MAT_04', 'Ensaio de Tração', 2, true),
  ('CIE_MAT_04_003', 'CIE_MAT_04', 'Ensaios de Dureza', 3, true),
  ('CIE_MAT_04_004', 'CIE_MAT_04', 'Ensaios Não Destrutivos', 4, true),
  ('CIE_MAT_05_001', 'CIE_MAT_05', 'Alotropia e Polimorfismo', 1, true),
  ('CIE_MAT_05_002', 'CIE_MAT_05', 'Defeitos Cristalinos', 2, true),
  ('CIE_MAT_05_003', 'CIE_MAT_05', 'Fator de Empacotamento Atômico', 3, true),
  ('CIE_MAT_05_004', 'CIE_MAT_05', 'Redes e Células Cristalinas', 4, true),
  ('CIE_MAT_05_005', 'CIE_MAT_05', 'Sistemas Cristalinos', 5, true),
  ('CIE_MAT_06_001', 'CIE_MAT_06', 'Fadiga', 1, true),
  ('CIE_MAT_06_002', 'CIE_MAT_06', 'Fluência', 2, true),
  ('CIE_MAT_06_003', 'CIE_MAT_06', 'Fratura', 3, true),
  ('CIE_MAT_06_004', 'CIE_MAT_06', 'Tenacidade à Fratura', 4, true),
  ('CIE_MAT_07_001', 'CIE_MAT_07', 'Estrutura e Propriedades dos Polímeros', 1, true),
  ('CIE_MAT_07_002', 'CIE_MAT_07', 'Materiais Cerâmicos, Refratários e Vidros', 2, true),
  ('CIE_MAT_07_003', 'CIE_MAT_07', 'Termoplásticos e Termofixos', 3, true),
  ('CIE_MAT_08_001', 'CIE_MAT_08', 'Aços', 1, true),
  ('CIE_MAT_08_002', 'CIE_MAT_08', 'Ferros Fundidos', 2, true),
  ('CIE_MAT_08_003', 'CIE_MAT_08', 'Ligas de Alumínio', 3, true),
  ('CIE_MAT_08_004', 'CIE_MAT_08', 'Ligas Não Ferrosas', 4, true),
  ('CIE_MAT_09_001', 'CIE_MAT_09', 'Encruamento', 1, true),
  ('CIE_MAT_09_002', 'CIE_MAT_09', 'Refino de Grão', 2, true),
  ('CIE_MAT_10_001', 'CIE_MAT_10', 'Propriedades Elétricas', 1, true),
  ('CIE_MAT_10_002', 'CIE_MAT_10', 'Propriedades Magnéticas', 2, true),
  ('CIE_MAT_10_003', 'CIE_MAT_10', 'Propriedades Térmicas', 3, true),
  ('CIE_MAT_11_001', 'CIE_MAT_11', 'Ductilidade e Tenacidade', 1, true),
  ('CIE_MAT_11_002', 'CIE_MAT_11', 'Elasticidade', 2, true),
  ('CIE_MAT_11_003', 'CIE_MAT_11', 'Plasticidade', 3, true),
  ('CIE_MAT_11_004', 'CIE_MAT_11', 'Resistência e Dureza', 4, true),
  ('CIE_MAT_12_001', 'CIE_MAT_12', 'Recozimento e Normalização', 1, true),
  ('CIE_MAT_12_002', 'CIE_MAT_12', 'Têmpera e Revenimento', 2, true),
  ('CIE_MAT_12_003', 'CIE_MAT_12', 'Transformações Martensíticas', 3, true),
  ('CIE_MAT_12_004', 'CIE_MAT_12', 'Tratamentos Termoquímicos', 4, true),
  ('DES_TEC_01_001', 'DES_TEC_01', 'Camadas e Propriedades', 1, true),
  ('DES_TEC_01_002', 'DES_TEC_01', 'Coordenadas em CAD', 2, true),
  ('DES_TEC_01_003', 'DES_TEC_01', 'Desenho e Edição', 3, true),
  ('DES_TEC_01_004', 'DES_TEC_01', 'Espaços de Trabalho e Layout', 4, true),
  ('DES_TEC_01_005', 'DES_TEC_01', 'Fundamentos de CAD', 5, true),
  ('DES_TEC_01_006', 'DES_TEC_01', 'Modelagem 2D e 3D', 6, true),
  ('DES_TEC_01_007', 'DES_TEC_01', 'Plotagem e Impressão', 7, true),
  ('DES_TEC_02_001', 'DES_TEC_02', 'Cotagem e Dimensionamento', 1, true),
  ('DES_TEC_02_002', 'DES_TEC_02', 'Escalas', 2, true),
  ('DES_TEC_02_003', 'DES_TEC_02', 'Normas e Convenções de Desenho', 3, true),
  ('DES_TEC_02_004', 'DES_TEC_02', 'Tolerâncias, Ajustes e Estado de Superfície', 4, true),
  ('DES_TEC_03_001', 'DES_TEC_03', 'Cortes e Seções', 1, true),
  ('DES_TEC_03_002', 'DES_TEC_03', 'Geometria Descritiva', 2, true),
  ('DES_TEC_03_003', 'DES_TEC_03', 'Perspectivas', 3, true),
  ('DES_TEC_03_004', 'DES_TEC_03', 'Sistemas de Projeção e Vistas', 4, true),
  ('ENG_ECO_01_001', 'ENG_ECO_01', 'Custo Anual Equivalente', 1, true),
  ('ENG_ECO_01_002', 'ENG_ECO_01', 'Depreciação', 2, true),
  ('ENG_ECO_01_003', 'ENG_ECO_01', 'Fluxos de Caixa', 3, true),
  ('ENG_ECO_01_004', 'ENG_ECO_01', 'Payback', 4, true),
  ('ENG_ECO_01_005', 'ENG_ECO_01', 'Taxa Interna de Retorno', 5, true),
  ('ENG_ECO_01_006', 'ENG_ECO_01', 'Valor Presente Líquido', 6, true),
  ('ENG_ECO_02_001', 'ENG_ECO_02', 'Descontos', 1, true),
  ('ENG_ECO_02_002', 'ENG_ECO_02', 'Equivalência de Capitais', 2, true),
  ('ENG_ECO_02_003', 'ENG_ECO_02', 'Juros Compostos', 3, true),
  ('ENG_ECO_02_004', 'ENG_ECO_02', 'Juros Simples', 4, true),
  ('ENG_ECO_02_005', 'ENG_ECO_02', 'Séries Uniformes de Pagamentos', 5, true),
  ('ENG_ECO_02_006', 'ENG_ECO_02', 'Sistemas de Amortização', 6, true),
  ('ENG_ECO_02_007', 'ENG_ECO_02', 'Taxas de Juros', 7, true),
  ('FIS_GER_01_001', 'FIS_GER_01', 'Associação de Resistores', 1, true),
  ('FIS_GER_01_002', 'FIS_GER_01', 'Circuitos de Corrente Contínua', 2, true),
  ('FIS_GER_01_003', 'FIS_GER_01', 'Corrente, Resistência e Lei de Ohm', 3, true),
  ('FIS_GER_01_004', 'FIS_GER_01', 'Potência e Energia Elétrica', 4, true),
  ('FIS_GER_02_001', 'FIS_GER_02', 'Campo Elétrico', 1, true),
  ('FIS_GER_02_002', 'FIS_GER_02', 'Capacitância e Capacitores', 2, true),
  ('FIS_GER_02_003', 'FIS_GER_02', 'Carga Elétrica e Lei de Coulomb', 3, true),
  ('FIS_GER_02_004', 'FIS_GER_02', 'Potencial Elétrico', 4, true),
  ('FIS_GER_03_001', 'FIS_GER_03', 'Estrutura Atômica e Física Nuclear', 1, true),
  ('FIS_GER_04_001', 'FIS_GER_04', 'Campo Magnético', 1, true),
  ('FIS_GER_04_002', 'FIS_GER_04', 'Força Magnética', 2, true),
  ('FIS_GER_04_003', 'FIS_GER_04', 'Indução Eletromagnética e Lei de Faraday-Lenz', 3, true),
  ('FIS_GER_05_001', 'FIS_GER_05', 'Acústica', 1, true),
  ('FIS_GER_05_002', 'FIS_GER_05', 'Fenômenos Ondulatórios', 2, true),
  ('FIS_GER_05_003', 'FIS_GER_05', 'Ondas Mecânicas', 3, true),
  ('FIS_GER_05_004', 'FIS_GER_05', 'Óptica Geométrica', 4, true),
  ('MAT_BAS_01_001', 'MAT_BAS_01', 'Equações do 1º Grau', 1, true),
  ('MAT_BAS_01_002', 'MAT_BAS_01', 'Equações do 2º Grau', 2, true),
  ('MAT_BAS_01_003', 'MAT_BAS_01', 'Inequações', 3, true),
  ('MAT_BAS_01_004', 'MAT_BAS_01', 'Sistemas de Equações do 1º Grau', 4, true),
  ('MAT_BAS_02_001', 'MAT_BAS_02', 'Arranjos', 1, true),
  ('MAT_BAS_02_002', 'MAT_BAS_02', 'Combinações', 2, true),
  ('MAT_BAS_02_003', 'MAT_BAS_02', 'Permutações', 3, true),
  ('MAT_BAS_02_004', 'MAT_BAS_02', 'Princípio Fundamental da Contagem', 4, true),
  ('MAT_BAS_03_001', 'MAT_BAS_03', 'Divisão Proporcional', 1, true),
  ('MAT_BAS_03_002', 'MAT_BAS_03', 'Divisibilidade', 2, true),
  ('MAT_BAS_03_003', 'MAT_BAS_03', 'Frações', 3, true),
  ('MAT_BAS_03_004', 'MAT_BAS_03', 'MDC e MMC', 4, true),
  ('MAT_BAS_03_005', 'MAT_BAS_03', 'Operações Fundamentais', 5, true),
  ('MAT_BAS_03_006', 'MAT_BAS_03', 'Porcentagem', 6, true),
  ('MAT_BAS_03_007', 'MAT_BAS_03', 'Potenciação e Radiciação', 7, true),
  ('MAT_BAS_03_008', 'MAT_BAS_03', 'Razões e Proporções', 8, true),
  ('MAT_BAS_03_009', 'MAT_BAS_03', 'Regra de Três', 9, true),
  ('MAT_BAS_03_010', 'MAT_BAS_03', 'Unidades e Conversões', 10, true),
  ('MAT_BAS_04_001', 'MAT_BAS_04', 'Função Afim', 1, true),
  ('MAT_BAS_04_002', 'MAT_BAS_04', 'Função Exponencial', 2, true),
  ('MAT_BAS_04_003', 'MAT_BAS_04', 'Função Logarítmica', 3, true),
  ('MAT_BAS_04_004', 'MAT_BAS_04', 'Função Quadrática', 4, true),
  ('MAT_BAS_04_005', 'MAT_BAS_04', 'Propriedades e Operações com Funções', 5, true),
  ('MAT_BAS_05_001', 'MAT_BAS_05', 'Cônicas e Circunferência', 1, true),
  ('MAT_BAS_05_002', 'MAT_BAS_05', 'Retas no Plano', 2, true),
  ('MAT_BAS_05_003', 'MAT_BAS_05', 'Sistemas de Coordenadas e Geometria Espacial', 3, true),
  ('MAT_BAS_05_004', 'MAT_BAS_05', 'Vetores e Operações Vetoriais', 4, true),
  ('MAT_BAS_06_001', 'MAT_BAS_06', 'Áreas e Volumes', 1, true),
  ('MAT_BAS_06_002', 'MAT_BAS_06', 'Cilindros', 2, true),
  ('MAT_BAS_06_003', 'MAT_BAS_06', 'Cones', 3, true),
  ('MAT_BAS_06_004', 'MAT_BAS_06', 'Esferas', 4, true),
  ('MAT_BAS_06_005', 'MAT_BAS_06', 'Prismas, Pirâmides e Poliedros', 5, true),
  ('MAT_BAS_06_006', 'MAT_BAS_06', 'Troncos', 6, true),
  ('MAT_BAS_07_001', 'MAT_BAS_07', 'Áreas e Perímetros', 1, true),
  ('MAT_BAS_07_002', 'MAT_BAS_07', 'Circunferência e Círculo', 2, true),
  ('MAT_BAS_07_003', 'MAT_BAS_07', 'Semelhança e Teorema de Tales', 3, true),
  ('MAT_BAS_07_004', 'MAT_BAS_07', 'Teorema de Pitágoras', 4, true),
  ('MAT_BAS_08_001', 'MAT_BAS_08', 'Progressão Aritmética', 1, true),
  ('MAT_BAS_08_002', 'MAT_BAS_08', 'Progressão Geométrica', 2, true),
  ('MAT_BAS_08_003', 'MAT_BAS_08', 'Sequências Recorrentes', 3, true),
  ('MAT_BAS_09_001', 'MAT_BAS_09', 'Diagramas de Venn', 1, true),
  ('MAT_BAS_09_002', 'MAT_BAS_09', 'Operações com Conjuntos', 2, true),
  ('MAT_BAS_09_003', 'MAT_BAS_09', 'Relações de Pertinência e Inclusão', 3, true),
  ('MAT_BAS_10_001', 'MAT_BAS_10', 'Equações Trigonométricas', 1, true),
  ('MAT_BAS_10_002', 'MAT_BAS_10', 'Funções Trigonométricas', 2, true),
  ('MAT_BAS_10_003', 'MAT_BAS_10', 'Identidades Trigonométricas', 3, true),
  ('MAT_BAS_10_004', 'MAT_BAS_10', 'Leis dos Senos e Cossenos', 4, true),
  ('MAT_BAS_10_005', 'MAT_BAS_10', 'Trigonometria em Triângulos', 5, true),
  ('MEC_FLU_01_001', 'MEC_FLU_01', 'Homogeneidade Dimensional', 1, true),
  ('MEC_FLU_01_002', 'MEC_FLU_01', 'Números Adimensionais', 2, true),
  ('MEC_FLU_01_003', 'MEC_FLU_01', 'Teorema de Buckingham Pi', 3, true),
  ('MEC_FLU_01_004', 'MEC_FLU_01', 'Teoria de Modelos e Semelhança', 4, true),
  ('MEC_FLU_02_001', 'MEC_FLU_02', 'Campo de Velocidade', 1, true),
  ('MEC_FLU_02_002', 'MEC_FLU_02', 'Vazão e Velocidade Média', 2, true),
  ('MEC_FLU_03_001', 'MEC_FLU_03', 'Conservação da Massa e Equação da Continuidade', 1, true),
  ('MEC_FLU_03_002', 'MEC_FLU_03', 'Equação de Bernoulli', 2, true),
  ('MEC_FLU_03_003', 'MEC_FLU_03', 'Quantidade de Movimento', 3, true),
  ('MEC_FLU_03_004', 'MEC_FLU_03', 'Volume de Controle', 4, true),
  ('MEC_FLU_04_001', 'MEC_FLU_04', 'Arrasto', 1, true),
  ('MEC_FLU_04_002', 'MEC_FLU_04', 'Camada Limite', 2, true),
  ('MEC_FLU_05_001', 'MEC_FLU_05', 'Cavitação', 1, true),
  ('MEC_FLU_05_002', 'MEC_FLU_05', 'Equação de Hagen-Poiseuille', 2, true),
  ('MEC_FLU_05_003', 'MEC_FLU_05', 'Fator de Atrito', 3, true),
  ('MEC_FLU_05_004', 'MEC_FLU_05', 'Número de Reynolds', 4, true),
  ('MEC_FLU_05_005', 'MEC_FLU_05', 'Perdas de Carga e Equação de Darcy-Weisbach', 5, true),
  ('MEC_FLU_05_006', 'MEC_FLU_05', 'Regimes Laminar e Turbulento', 6, true),
  ('MEC_FLU_05_007', 'MEC_FLU_05', 'Sistemas de Tubulações', 7, true),
  ('MEC_FLU_06_001', 'MEC_FLU_06', 'Empuxo e Princípio de Arquimedes', 1, true),
  ('MEC_FLU_06_002', 'MEC_FLU_06', 'Forças Hidrostáticas', 2, true),
  ('MEC_FLU_06_003', 'MEC_FLU_06', 'Manometria', 3, true),
  ('MEC_FLU_06_004', 'MEC_FLU_06', 'Pressão Hidrostática e Teorema de Stevin', 4, true),
  ('MEC_FLU_06_005', 'MEC_FLU_06', 'Princípio de Pascal', 5, true),
  ('MEC_FLU_07_001', 'MEC_FLU_07', 'Outros Medidores de Vazão', 1, true),
  ('MEC_FLU_07_002', 'MEC_FLU_07', 'Placa de Orifício', 2, true),
  ('MEC_FLU_07_003', 'MEC_FLU_07', 'Tubo de Pitot', 3, true),
  ('MEC_FLU_07_004', 'MEC_FLU_07', 'Tubo de Venturi', 4, true),
  ('MEC_FLU_08_001', 'MEC_FLU_08', 'Compressibilidade', 1, true),
  ('MEC_FLU_08_002', 'MEC_FLU_08', 'Fluidos Newtonianos e Não Newtonianos', 2, true),
  ('MEC_FLU_08_003', 'MEC_FLU_08', 'Massa Específica, Peso Específico e Densidade', 3, true),
  ('MEC_FLU_08_004', 'MEC_FLU_08', 'Tensão Superficial e Capilaridade', 4, true),
  ('MEC_FLU_08_005', 'MEC_FLU_08', 'Viscosidade', 5, true),
  ('MEC_GER_01_001', 'MEC_GER_01', 'Movimento Circular', 1, true),
  ('MEC_GER_01_002', 'MEC_GER_01', 'Movimento Curvilíneo', 2, true),
  ('MEC_GER_01_003', 'MEC_GER_01', 'Movimento Retilíneo', 3, true),
  ('MEC_GER_02_001', 'MEC_GER_02', 'Movimento Plano', 1, true),
  ('MEC_GER_02_002', 'MEC_GER_02', 'Rotação em Eixo Fixo', 2, true),
  ('MEC_GER_03_001', 'MEC_GER_03', 'Impulso e Quantidade de Movimento', 1, true),
  ('MEC_GER_03_002', 'MEC_GER_03', 'Leis de Newton', 2, true),
  ('MEC_GER_03_003', 'MEC_GER_03', 'Trabalho e Energia', 3, true),
  ('MEC_GER_04_001', 'MEC_GER_04', 'Equações do Movimento', 1, true),
  ('MEC_GER_04_002', 'MEC_GER_04', 'Momento de Inércia de Massa', 2, true),
  ('MEC_GER_05_001', 'MEC_GER_05', 'Atrito', 1, true),
  ('MEC_GER_05_002', 'MEC_GER_05', 'Centroides e Centros de Massa', 2, true),
  ('MEC_GER_05_003', 'MEC_GER_05', 'Equilíbrio de Corpos Rígidos', 3, true),
  ('MEC_GER_05_004', 'MEC_GER_05', 'Momentos e Binários', 4, true),
  ('MEC_GER_05_005', 'MEC_GER_05', 'Reações de Apoio', 5, true),
  ('METROL_01_001', 'METROL_01', 'Calibração', 1, true),
  ('METROL_01_002', 'METROL_01', 'Rastreabilidade', 2, true),
  ('METROL_02_001', 'METROL_02', 'Erros Aleatórios e Sistemáticos', 1, true),
  ('METROL_02_002', 'METROL_02', 'Incerteza de Medição', 2, true),
  ('METROL_03_001', 'METROL_03', 'Conceitos Fundamentais', 1, true),
  ('METROL_03_002', 'METROL_03', 'Exatidão, Precisão, Repetibilidade e Reprodutibilidade', 2, true),
  ('METROL_04_001', 'METROL_04', 'Instrumentos de Medição Dimensional', 1, true),
  ('METROL_04_002', 'METROL_04', 'Sensores e Transdutores', 2, true),
  ('METROL_05_001', 'METROL_05', 'Grandezas e Unidades', 1, true),
  ('METROL_05_002', 'METROL_05', 'Prefixos e Conversões', 2, true),
  ('METROL_05_003', 'METROL_05', 'Unidades SI', 3, true),
  ('METROL_06_001', 'METROL_06', 'Folgas, Interferências e Tolerância Dimensional', 1, true),
  ('METROL_06_002', 'METROL_06', 'Sistema de Ajustes (Furo-Base e Eixo-Base)', 2, true),
  ('PRB_EST_01_001', 'PRB_EST_01', 'Coeficientes de Ajuste e Determinação', 1, true),
  ('PRB_EST_01_002', 'PRB_EST_01', 'Correlação, Covariância e Diagrama de Dispersão', 2, true),
  ('PRB_EST_01_003', 'PRB_EST_01', 'Interpretação e Ajuste de Modelos Lineares', 3, true),
  ('PRB_EST_01_004', 'PRB_EST_01', 'Regressão Linear e Mínimos Quadrados', 4, true),
  ('PRB_EST_02_001', 'PRB_EST_02', 'Boxplot, Quartis e Outliers', 1, true),
  ('PRB_EST_02_002', 'PRB_EST_02', 'Gráficos, Tabelas e Tendências', 2, true),
  ('PRB_EST_02_003', 'PRB_EST_02', 'Medidas de Dispersão e Forma', 3, true),
  ('PRB_EST_02_004', 'PRB_EST_02', 'Medidas de Tendência Central', 4, true),
  ('PRB_EST_03_001', 'PRB_EST_03', 'Amostragem Estatística', 1, true),
  ('PRB_EST_03_002', 'PRB_EST_03', 'Delineamento Experimental e ANOVA', 2, true),
  ('PRB_EST_03_003', 'PRB_EST_03', 'Distribuições Amostrais e Estimação', 3, true),
  ('PRB_EST_03_004', 'PRB_EST_03', 'Intervalos de Confiança', 4, true),
  ('PRB_EST_03_005', 'PRB_EST_03', 'Testes de Hipóteses e Significância', 5, true),
  ('PRB_EST_04_001', 'PRB_EST_04', 'Árvores de Eventos', 1, true),
  ('PRB_EST_04_002', 'PRB_EST_04', 'Fundamentos, Espaço Amostral e Axiomas', 2, true),
  ('PRB_EST_04_003', 'PRB_EST_04', 'Independência, Dependência e Ensaios Sucessivos', 3, true),
  ('PRB_EST_04_004', 'PRB_EST_04', 'Operações com Eventos', 4, true),
  ('PRB_EST_04_005', 'PRB_EST_04', 'Probabilidade Clássica e Métodos Combinatórios', 5, true),
  ('PRB_EST_04_006', 'PRB_EST_04', 'Probabilidade Condicional, Bayes e Probabilidade Total', 6, true),
  ('PRB_EST_04_007', 'PRB_EST_04', 'Probabilidade em Amostragem Finita', 7, true),
  ('PRB_EST_05_001', 'PRB_EST_05', 'Conceitos Gerais de Variáveis Aleatórias', 1, true),
  ('PRB_EST_05_002', 'PRB_EST_05', 'Distribuição Binomial e Bernoulli', 2, true),
  ('PRB_EST_05_003', 'PRB_EST_05', 'Distribuição de Poisson', 3, true),
  ('PRB_EST_05_004', 'PRB_EST_05', 'Distribuição Exponencial e Weibull', 4, true),
  ('PRB_EST_05_005', 'PRB_EST_05', 'Distribuição Geométrica', 5, true),
  ('PRB_EST_05_006', 'PRB_EST_05', 'Distribuição Hipergeométrica', 6, true),
  ('PRB_EST_05_007', 'PRB_EST_05', 'Distribuição Normal e Teorema Central do Limite', 7, true),
  ('PRB_EST_05_008', 'PRB_EST_05', 'Esperança, Variância e Momentos', 8, true),
  ('PRB_EST_05_009', 'PRB_EST_05', 'Função de Distribuição e Densidade de Probabilidade', 9, true),
  ('QUI_GER_01_001', 'QUI_GER_01', 'Fatores que Afetam a Velocidade de Reação', 1, true),
  ('QUI_GER_01_002', 'QUI_GER_01', 'Lei de Velocidade, Ordem de Reação e Arrhenius', 2, true),
  ('QUI_GER_02_001', 'QUI_GER_02', 'Eletrólise', 1, true),
  ('QUI_GER_02_002', 'QUI_GER_02', 'Oxidação e Redução', 2, true),
  ('QUI_GER_02_003', 'QUI_GER_02', 'Pilhas e Potenciais Eletroquímicos', 3, true),
  ('QUI_GER_03_001', 'QUI_GER_03', 'Equilíbrio Ácido-Base', 1, true),
  ('QUI_GER_03_002', 'QUI_GER_03', 'Equilíbrio de Solubilidade', 2, true),
  ('QUI_GER_03_003', 'QUI_GER_03', 'Equilíbrio Químico e Constantes', 3, true),
  ('QUI_GER_03_004', 'QUI_GER_03', 'Princípio de Le Chatelier', 4, true),
  ('QUI_GER_04_001', 'QUI_GER_04', 'Cálculos Estequiométricos', 1, true),
  ('QUI_GER_04_002', 'QUI_GER_04', 'Reagente Limitante e Rendimento', 2, true),
  ('QUI_GER_05_001', 'QUI_GER_05', 'Estrutura Atômica', 1, true),
  ('QUI_GER_05_002', 'QUI_GER_05', 'Ligações Químicas e Geometria Molecular', 2, true),
  ('QUI_GER_05_003', 'QUI_GER_05', 'Propriedades Periódicas', 3, true),
  ('QUI_GER_06_001', 'QUI_GER_06', 'Funções Inorgânicas', 1, true),
  ('QUI_GER_07_001', 'QUI_GER_07', 'Concentração de Soluções', 1, true),
  ('QUI_GER_07_002', 'QUI_GER_07', 'Diluição e Mistura de Soluções', 2, true),
  ('QUI_GER_07_003', 'QUI_GER_07', 'Propriedades das Soluções', 3, true),
  ('RES_MAT_01_001', 'RES_MAT_01', 'Critério de Rankine', 1, true),
  ('RES_MAT_01_002', 'RES_MAT_01', 'Critério de Tresca', 2, true),
  ('RES_MAT_01_003', 'RES_MAT_01', 'Critério de von Mises', 3, true),
  ('RES_MAT_01_004', 'RES_MAT_01', 'Critérios de Mohr', 4, true),
  ('RES_MAT_02_001', 'RES_MAT_02', 'Diagramas de Esforços Internos', 1, true),
  ('RES_MAT_02_002', 'RES_MAT_02', 'Esforço Cortante', 2, true),
  ('RES_MAT_02_003', 'RES_MAT_02', 'Esforço Normal', 3, true),
  ('RES_MAT_02_004', 'RES_MAT_02', 'Momento Fletor', 4, true),
  ('RES_MAT_03_001', 'RES_MAT_03', 'Comprimento Efetivo', 1, true),
  ('RES_MAT_03_002', 'RES_MAT_03', 'Flambagem de Colunas e Carga Crítica de Euler', 2, true),
  ('RES_MAT_04_001', 'RES_MAT_04', 'Deflexão de Vigas e Linha Elástica', 1, true),
  ('RES_MAT_04_002', 'RES_MAT_04', 'Flexão em Vigas', 2, true),
  ('RES_MAT_05_001', 'RES_MAT_05', 'Centroide', 1, true),
  ('RES_MAT_05_002', 'RES_MAT_05', 'Momento de Inércia de Área', 2, true),
  ('RES_MAT_05_003', 'RES_MAT_05', 'Teorema dos Eixos Paralelos', 3, true),
  ('RES_MAT_06_001', 'RES_MAT_06', 'Carregamento Axial', 1, true),
  ('RES_MAT_06_002', 'RES_MAT_06', 'Deformação Axial', 2, true),
  ('RES_MAT_06_003', 'RES_MAT_06', 'Deformação e Tensão Térmica', 3, true),
  ('RES_MAT_06_004', 'RES_MAT_06', 'Lei de Hooke e Módulo de Elasticidade', 4, true),
  ('RES_MAT_06_005', 'RES_MAT_06', 'Razão de Poisson', 5, true),
  ('RES_MAT_06_006', 'RES_MAT_06', 'Tensão e Deformação', 6, true),
  ('RES_MAT_07_001', 'RES_MAT_07', 'Círculo de Mohr', 1, true),
  ('RES_MAT_07_002', 'RES_MAT_07', 'Tensões Principais', 2, true),
  ('RES_MAT_07_003', 'RES_MAT_07', 'Transformação de Tensões', 3, true),
  ('RES_MAT_07_004', 'RES_MAT_07', 'Vasos de Pressão de Parede Fina', 4, true),
  ('RES_MAT_08_001', 'RES_MAT_08', 'Ângulo de Torção', 1, true),
  ('RES_MAT_08_002', 'RES_MAT_08', 'Eixos Circulares', 2, true),
  ('TERMOD_01_001', 'TERMOD_01', 'Calor Sensível e Latente', 1, true),
  ('TERMOD_01_002', 'TERMOD_01', 'Capacidade Calorífica', 2, true),
  ('TERMOD_02_001', 'TERMOD_02', 'Ciclo Brayton', 1, true),
  ('TERMOD_02_002', 'TERMOD_02', 'Ciclo Diesel', 2, true),
  ('TERMOD_02_003', 'TERMOD_02', 'Ciclo Otto', 3, true),
  ('TERMOD_02_004', 'TERMOD_02', 'Ciclo Rankine', 4, true),
  ('TERMOD_02_005', 'TERMOD_02', 'Regeneração, Reaquecimento e Inter-resfriamento', 5, true),
  ('TERMOD_02_006', 'TERMOD_02', 'Rendimento Térmico de Ciclos', 6, true),
  ('TERMOD_03_001', 'TERMOD_03', 'Diagramas de Fases', 1, true),
  ('TERMOD_03_002', 'TERMOD_03', 'Lei de Raoult e Pontos de Bolha e Orvalho', 2, true),
  ('TERMOD_03_003', 'TERMOD_03', 'Regra das Fases de Gibbs e Potencial Químico', 3, true),
  ('TERMOD_04_001', 'TERMOD_04', 'Conceitos, Estado e Lei Zero', 1, true),
  ('TERMOD_04_002', 'TERMOD_04', 'Processos Termodinâmicos', 2, true),
  ('TERMOD_04_003', 'TERMOD_04', 'Propriedades Intensivas e Extensivas', 3, true),
  ('TERMOD_05_001', 'TERMOD_05', 'Equações de Estado de Gases Reais', 1, true),
  ('TERMOD_05_002', 'TERMOD_05', 'Fator de Compressibilidade', 2, true),
  ('TERMOD_05_003', 'TERMOD_05', 'Gás Ideal', 3, true),
  ('TERMOD_05_004', 'TERMOD_05', 'Misturas de Gases e Lei de Dalton', 4, true),
  ('TERMOD_06_001', 'TERMOD_06', 'Balanço de Energia em Sistemas Fechados', 1, true),
  ('TERMOD_06_002', 'TERMOD_06', 'Balanço de Energia em Volumes de Controle', 2, true),
  ('TERMOD_06_003', 'TERMOD_06', 'Efeito Joule-Thomson', 3, true),
  ('TERMOD_06_004', 'TERMOD_06', 'Entalpia e Energia Interna', 4, true),
  ('TERMOD_06_005', 'TERMOD_06', 'Equipamentos de Escoamento Permanente', 5, true),
  ('TERMOD_06_006', 'TERMOD_06', 'Trabalho e Calor', 6, true),
  ('TERMOD_07_001', 'TERMOD_07', 'Diagramas de Propriedades', 1, true),
  ('TERMOD_07_002', 'TERMOD_07', 'Estados de Saturação e Título', 2, true),
  ('TERMOD_07_003', 'TERMOD_07', 'Ponto Crítico e Ponto Triplo', 3, true),
  ('TERMOD_08_001', 'TERMOD_08', 'Carta Psicrométrica', 1, true),
  ('TERMOD_08_002', 'TERMOD_08', 'Processos Psicrométricos', 2, true),
  ('TERMOD_08_003', 'TERMOD_08', 'Umidade e Ponto de Orvalho', 3, true),
  ('TERMOD_09_001', 'TERMOD_09', 'Bombas de Calor', 1, true),
  ('TERMOD_09_002', 'TERMOD_09', 'Ciclo de Compressão de Vapor', 2, true),
  ('TERMOD_09_003', 'TERMOD_09', 'Coeficiente de Performance', 3, true),
  ('TERMOD_09_004', 'TERMOD_09', 'Refrigeração de Carnot', 4, true),
  ('TERMOD_10_001', 'TERMOD_10', 'Funções de Gibbs e Helmholtz', 1, true),
  ('TERMOD_10_002', 'TERMOD_10', 'Relações de Maxwell', 2, true),
  ('TERMOD_10_003', 'TERMOD_10', 'Relações entre Propriedades Termodinâmicas', 3, true),
  ('TERMOD_11_001', 'TERMOD_11', 'Ciclo de Carnot', 1, true),
  ('TERMOD_11_002', 'TERMOD_11', 'Entropia', 2, true),
  ('TERMOD_11_003', 'TERMOD_11', 'Irreversibilidade, Exergia e Rendimento de Segunda Lei', 3, true),
  ('TERMOD_12_001', 'TERMOD_12', 'Combustão Estequiométrica', 1, true),
  ('TERMOD_12_002', 'TERMOD_12', 'Entalpia de Formação e Reação', 2, true),
  ('TERMOD_12_003', 'TERMOD_12', 'Poder Calorífico', 3, true),
  ('TRA_CAL_01_001', 'TRA_CAL_01', 'Aletas', 1, true),
  ('TRA_CAL_01_002', 'TRA_CAL_01', 'Condução Cilíndrica', 2, true),
  ('TRA_CAL_01_003', 'TRA_CAL_01', 'Condução Transiente', 3, true),
  ('TRA_CAL_01_004', 'TRA_CAL_01', 'Condutividade e Difusividade Térmica', 4, true),
  ('TRA_CAL_01_005', 'TRA_CAL_01', 'Geração Interna de Calor', 5, true),
  ('TRA_CAL_01_006', 'TRA_CAL_01', 'Lei de Fourier', 6, true),
  ('TRA_CAL_01_007', 'TRA_CAL_01', 'Paredes Compostas', 7, true),
  ('TRA_CAL_02_001', 'TRA_CAL_02', 'Convecção com Mudança de Fase', 1, true),
  ('TRA_CAL_02_002', 'TRA_CAL_02', 'Convecção Forçada', 2, true),
  ('TRA_CAL_02_003', 'TRA_CAL_02', 'Convecção Natural', 3, true),
  ('TRA_CAL_02_004', 'TRA_CAL_02', 'Números de Nusselt, Reynolds e Prandtl', 4, true),
  ('TRA_CAL_03_001', 'TRA_CAL_03', 'Mecanismos de Transferência de Calor', 1, true),
  ('TRA_CAL_03_002', 'TRA_CAL_03', 'Resistência Térmica', 2, true),
  ('TRA_CAL_04_001', 'TRA_CAL_04', 'Corpo Negro e Lei de Stefan-Boltzmann', 1, true),
  ('TRA_CAL_04_002', 'TRA_CAL_04', 'Fatores de Forma e Troca Radiativa', 2, true),
  ('TRA_CAL_04_003', 'TRA_CAL_04', 'Propriedades Radiativas', 3, true),
  ('TRA_CAL_05_001', 'TRA_CAL_05', 'Balanço de Energia em Trocadores', 1, true),
  ('TRA_CAL_05_002', 'TRA_CAL_05', 'Configurações de Trocadores', 2, true),
  ('TRA_CAL_05_003', 'TRA_CAL_05', 'Efetividade e Método NTU', 3, true),
  ('TRA_CAL_05_004', 'TRA_CAL_05', 'Método da Diferença de Temperatura Média Logarítmica', 4, true)
on conflict (subassunto_id) do update
  set assunto_id = excluded.assunto_id, name = excluded.name, ordem = excluded.ordem, ativo = true;

commit;
